### ISSUE TITLE
Wapiti Error

### ISSUE THREAD

**Issue by CreativeWolf** [BlackArch/blackarch#1020]
Heya,

I'm getting this error message while running wapiti

Traceback (most recent call last):
  File "/usr/bin/wapiti", line 41, in <module>
    lan.configure()
  File "/usr/lib/python2.7/site-packages/wapitiCore/language/language.py", line 58, in configure
    lang = langCounty[:2]  # en
TypeError: 'NoneType' object has no attribute '__getitem__'

Any pointers how to fix this please?

**Comment by noptrix** [comment]
Did you try sth similar like export LANG="en_US"?
