### ISSUE TITLE
mitmproxy failing to start

### ISSUE THREAD

**Issue by kurobeats** [BlackArch/blackarch#1045]
mitmproxy doesn't seem to be finding python2-pillow-3.2.0-1:

```
Traceback (most recent call last):
  File "/usr/bin/mitmproxy", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2900, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2886, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2913, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 637, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 650, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 829, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'Pillow<3.2,>=3.1' distribution was not found and is required by mitmproxy
```

**Comment by kurobeats** [comment]
Ah the offender is /usr/lib/python2.7/site-packages/mitmproxy-0.16-py2.7.egg-info/requires.txt

Unsure how you want to handle it, but modifying the Pillow version restrictions works for me.

**Comment by kurobeats** [comment]
resolved
