### ISSUE TITLE
[BUG] lfi_fuzzploit

### ISSUE THREAD

**Issue by Anyon3** [BlackArch/blackarch#1099]
> Traceback (most recent call last):
  File "/usr/bin/lfi_fuzzploit", line 858, in <module>
    sys.exit(main())
  File "/usr/bin/lfi_fuzzploit", line 275, in main
    scanner(myurl,url,htmlfile)
  File "/usr/bin/lfi_fuzzploit", line 688, in scanner
    response = urllib2.urlopen(req, timeout=10)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1195, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1096, in _send_request
    self.putheader(hdr, value)
  File "/usr/lib/python2.7/httplib.py", line 1030, in putheader
    raise ValueError('Invalid header name %r' % (header,))

> Traceback (most recent call last):
  File "/usr/bin/lfi_fuzzploit", line 858, in <module>
    sys.exit(main())
  File "/usr/bin/lfi_fuzzploit", line 275, in main
    scanner(myurl,url,htmlfile)
  File "/usr/bin/lfi_fuzzploit", line 688, in scanner
    response = urllib2.urlopen(req, timeout=10)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1228, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1195, in do_open
    h.request(req.get_method(), req.get_selector(), req.data, headers)
  File "/usr/lib/python2.7/httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python2.7/httplib.py", line 1096, in _send_request
    self.putheader(hdr, value)
  File "/usr/lib/python2.7/httplib.py", line 1030, in putheader
    raise ValueError('Invalid header name %r' % (header,))
ValueError: Invalid header name 'Referer: '

.....

Attached file fix those error
[lfifix.txt](https://github.com/BlackArch/blackarch/files/380158/lfifix.txt)

**Comment by noptrix** [comment]
thx! patched and released
