### ISSUE TITLE
[TOOL BUG] spiderfoot: the package doesn't work at all

### ISSUE THREAD

**Issue by nil0x42** [BlackArch/blackarch#1118]
### python exception when trying to run spiderfoot

`$ spiderfoot`
```
Starting web server at http://127.0.0.1:5001 ...
Traceback (most recent call last):
  File "sf.py", line 157, in <module>
    cherrypy.quickstart(SpiderFootWebUi(sfConfig), script_name=sfConfig['__docroot'], config=conf)
  File "/usr/share/spiderfoot/sfwebui.py", line 37, in __init__
    dbh = SpiderFootDb(self.defaultConfig)
  File "/usr/share/spiderfoot/sfdb.py", line 205, in __init__
    dbh = sqlite3.connect(self.sf.myPath() + "/" + opts['__database'], timeout=10)
sqlite3.OperationalError: unable to open database file
```

unfortunately, i had no time to fix it, the inly thing i know is that the error happens when the tool tries to open a non-existent sqlite file: `/usr/share/spiderfoot/spiderfoot.db`

**Comment by noptrix** [comment]
Should be fixed. Though, you need to run it as root, since it's trying to write/create in /usr/share/spiderfoot/ Also, I've upgraded hte version as well.

**Comment by svrmnnk** [comment]
i have the same problem, even running as a root user yields a huge error log which starts with
```
[2023-06-08 05:00:02,820 [ERROR] sflib : Exception (OSError) in module sfp_tool_wafw00f.Traceback (most recent call last):
  File "/usr/.../spiderfoot/db.py", line 318, in __init__
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/.../spiderfoot/db.py", line 502, in threadWorker
  File "/usr/.../spiderfoot/db.py", line 320, in __init__
OSError: Error connecting to internal database /var/root/.spiderfoot//spiderfoot.db](url)
```

this block repeats itself many times and then other errors come up
