### ISSUE TITLE
[NO WORKING] python2-claripy package

### ISSUE THREAD

**Issue by nil0x42** [BlackArch/blackarch#1284]
# Issue:

python2-claripy cannot be launched.
Discovered while trying to run `angr` package, which depends on `python2-claripy`.

# Steps to reproduce

### importing claripy from python:
**`$ python2`**
```python
Python 2.7.13 (default, Dec 21 2016, 07:16:46)
[GCC 6.2.1 20160830] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import claripy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/claripy/__init__.py", line 16, in <module>
    from . import backends as _backends_module
  File "/usr/lib/python2.7/site-packages/claripy/backends/__init__.py", line 715, in <module>
    from .backend_z3 import BackendZ3
  File "/usr/lib/python2.7/site-packages/claripy/backends/backend_z3.py", line 24, in <module>
    import z3
ImportError: No module named z3
```

### importing claripy from angr:
**`$ python2`**
```python
Python 2.7.13 (default, Dec 21 2016, 07:16:46)
[GCC 6.2.1 20160830] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import angr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/angr/__init__.py", line 7, in <module>
    from .project import *
  File "/usr/lib/python2.7/site-packages/angr/project.py", line 11, in <module>
    import simuvex
  File "/usr/lib/python2.7/site-packages/simuvex/__init__.py", line 12, in <module>
    from .s_state import SimState
  File "/usr/lib/python2.7/site-packages/simuvex/s_state.py", line 11, in <module>
    import claripy
  File "/usr/lib/python2.7/site-packages/claripy/__init__.py", line 12, in <module>
    from . import operations
ImportError: cannot import name operations
```

**Comment by noptrix** [comment]
thanks, will be fixed :)

**Comment by nil0x42** [comment]
claripy depends on blackarch/z3
adding this as a dependency fixes `import claripy`.

**Comment by noptrix** [comment]
thanks. z3 added as dep. released.
