### ISSUE TITLE
[NOT WORKING] angr

### ISSUE THREAD

**Issue by nil0x42** [BlackArch/blackarch#1292]
# Issue
after explicitly installing `z3` (which is a dependency of python-claripy missing in the package), i still have this error:
**`$ python2`**
```python
>>> import angr
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    import angr
  File "/usr/lib/python2.7/site-packages/bpython/curtsiesfrontend/repl.py", line 257, in load_module
    module = pkgutil.ImpLoader.load_module(self, name)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/usr/lib/python2.7/site-packages/angr/__init__.py", line 7, in <module>
    from .project import *
  File "/usr/lib/python2.7/site-packages/angr/project.py", line 562, in <module>
    from .factory import AngrObjectFactory
  File "/usr/lib/python2.7/site-packages/angr/factory.py", line 3, in <module>
    from .surveyors.caller import Callable
  File "/usr/lib/python2.7/site-packages/angr/surveyors/__init__.py", line 3, in <module>
    from .explorer import Explorer
  File "/usr/lib/python2.7/site-packages/angr/surveyors/explorer.py", line 8, in <module>
    from simuvex.s_errors import SimMemoryError, SimEngineError
ImportError: cannot import name SimEngineError
```

after looking at python2-simuvex sources, it looks that last version fron repository actually contains `SimEngineError` symbol, so updating `python2-simuvex` probably fixes the issue

**Comment by noptrix** [comment]
thanks. will be fixed

**Comment by noptrix** [comment]
compiler issues with new version of simuvex atm. but let's keep this ticket open

**Comment by max3raza** [comment]
Still see this issue.
Python 2.7.13 (default, Dec 21 2016, 07:16:46) 
[GCC 6.2.1 20160830] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import angr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/angr/__init__.py", line 7, in <module>
    from .project import *
  File "/usr/lib/python2.7/site-packages/angr/project.py", line 644, in <module>
    from .factory import AngrObjectFactory
  File "/usr/lib/python2.7/site-packages/angr/factory.py", line 3, in <module>
    from .surveyors.caller import Callable
  File "/usr/lib/python2.7/site-packages/angr/surveyors/__init__.py", line 3, in <module>
    from .explorer import Explorer
  File "/usr/lib/python2.7/site-packages/angr/surveyors/explorer.py", line 8, in <module>
    from simuvex.s_errors import SimMemoryError, SimEngineError
ImportError: cannot import name SimEngineError
>>>

**Comment by nil0x42** [comment]
yeah @max3raza , i have the same problem

**Comment by PedroSFreitas** [comment]
```
[ blackarch ~ ]# python2
Python 2.7.13 (default, Jul 21 2017, 03:24:34) 
[GCC 7.1.1 20170630] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import angr
>>>
```

Does anyone is still facing any issues? If so, it'd be interesting to provide any info and reopen the issue if necessary.

Thanks.

**Comment by max3raza** [comment]
I don't see this issue anymore.

**Comment by nil0x42** [comment]
me neither
