### ISSUE TITLE
apkid: Missing rules

### ISSUE THREAD

**Issue by vdun** [BlackArch/blackarch#1324]
```
# apkid test.apk
[+] APKiD 0.9.5 :: from RedNaga :: rednaga.io
Traceback (most recent call last):
  File "/usr/bin/apkid", line 11, in <module>
    load_entry_point('apkid==0.9.5', 'console_scripts', 'apkid')()
  File "/usr/lib/python2.7/site-packages/apkid/__init__.py", line 60, in main
    apkid.scan(input, args.timeout, args.json)
  File "/usr/lib/python2.7/site-packages/apkid/apkid.py", line 174, in scan
    rules = get_rules()
  File "/usr/lib/python2.7/site-packages/apkid/apkid.py", line 83, in get_rules
    return yara.load(rules_path)
yara.Error: could not open file "/usr/lib/python2.7/site-packages/apkid/rules/rules.yarc"
```

**Comment by noptrix** [comment]
where can we get this from?

**Comment by mrsmith0x00** [comment]
@vdun fixed. Thanks to @Edu4rdSHL.
