### ISSUE TITLE
Package Pythem

### ISSUE THREAD

**Issue by MatheusViGo** [BlackArch/blackarch#1529]
When executed show this error message:
"""Traceback (most recent call last):
  File "pythem.py", line 24, in <module>
    from core.interface import Processor
  File "/usr/share/pythem/core/interface.py", line 25, in <module>
    from modules.utils import *
  File "/usr/share/pythem/modules/utils.py", line 30, in <module>
    import termcolor
ImportError: No module named termcolor"""

#Repository updated and all dependencies satisfated

**Comment by noptrix** [comment]
fixed and released.

**Comment by MatheusViGo** [comment]
Cool, thanks !
