### ISSUE TITLE
Package SpiderFoot 

### ISSUE THREAD

**Issue by MatheusViGo** [BlackArch/blackarch#1531]
When executed show this error message:
"""Traceback (most recent call last):
  File "sf.py", line 31, in <module>
    __import__(mod)
  File "/usr/share/spiderfoot/ext/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/share/spiderfoot/ext/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/share/spiderfoot/ext/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'"""

#Repository updated and all dependencies satisfated

**Comment by noptrix** [comment]
thanks for reporting. we've fixed their own shit. the next release should include the fix hopefully. i've released our patched version.

**Comment by MatheusViGo** [comment]
Ok, thanks !
