### ISSUE TITLE
[Package] ghostphisher

### ISSUE THREAD

**Issue by gerardo-junior** [BlackArch/blackarch#1534]
executed show this error message:

  ~ ghostphisher                                                  
Traceback (most recent call last):
  File "/usr/share/ghostphisher/ghost.py", line 15, in <module>
    from gui import *
  File "/usr/share/ghostphisher/gui/ghost_phisher.py", line 24, in <module>
    from whats_new import whats_new_window
  File "/usr/share/ghostphisher/gui/whats_new.py", line 2, in <module>
    import whats_new_ui
  File "/usr/share/ghostphisher/gui/whats_new_ui.py", line 48, in <module>
    from PyQt4 import QtWebKit
ImportError: cannot import name QtWebKit

**Comment by saltasatelites** [comment]
Solution:
I don't know if that issue is already fixed.
In any case , It works for me:
Go to the ghostphisher directory, open /gui/whats_new_ui.py, and delete line 48 (the last one) = from PyQt4 import QtWebKit

Hope it helps you
disclaimer: Do it at your own risk. I've no responsibility if something go wrong, data loss, new bugs, software damaged or anything similar

**Comment by pantuts** [comment]
@saltasatelites i think you need to install QtWebKit module in python.

**Comment by saltasatelites** [comment]
@pantuts. Qtwebkit has created more than a headache in the last few months becouse is no longer supported by PyQt4, so install it for me have no sense. Sparta, fern-wifi-cracker, ghostphisher and others were affected by this issue. In all cases deleting QtWebKit have solved the problem. 
https://github.com/SECFORCE/sparta/issues/59.

**Comment by gerardo-junior** [comment]
Now, executed show this error message:

ghostphisher                
Traceback (most recent call last):
  File "/usr/share/ghostphisher/ghost.py", line 15, in <module>
    from gui import *
  File "/usr/share/ghostphisher/gui/ghost_phisher.py", line 16, in <module>
    from ghost_ui import *
  File "/usr/share/ghostphisher/gui/ghost_ui.py", line 12, in <module>
    setting_file = settings.Ghost_settings()
  File "/usr/share/ghostphisher/gui/settings.py", line 8, in __init__
    self._create_settings_directory()
  File "/usr/share/ghostphisher/gui/settings.py", line 17, in _create_settings_directory
    os.mkdir(self.cwd + os.sep + "Settings")

Is someone with this error too?

**Comment by saltasatelites** [comment]
Try  ``sudo python /usr/share/ghostphisher/ghost.py`` instead of `ghostphisher` directly

**Comment by gerardo-junior** [comment]
now this error appears:
sudo python /usr/share/ghostphisher/ghost.py
Traceback (most recent call last):
  File "/usr/share/ghostphisher/ghost.py", line 7, in <module>
    from PyQt4 import QtCore, QtGui
ModuleNotFoundError: No module named 'PyQt4'

it must be solved by adding the PyQt4 in the packet dependencies

**Comment by saltasatelites** [comment]
Read the first comments of this isue about PyQt4

**Comment by gerardo-junior** [comment]
yes, I'm sorry, fasthub must have found an aglum bug with cache.
