### ISSUE TITLE
[Error] Crackmapexec

### ISSUE THREAD

**Issue by MatheusViGo** [BlackArch/blackarch#1630]
When executed show this error message:
Traceback (most recent call last):
  File "/usr/bin/crackmapexec", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3036, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3020, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3049, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 654, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 968, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 854, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pylnk' distribution was not found and is required by crackmapexec

**Comment by noptrix** [comment]
@MatheusViGo hey, thanks for reporting. should be fixed now

**Comment by MatheusViGo** [comment]
Ok, thanks !
