### ISSUE TITLE
Canari dependencies non matched

### ISSUE THREAD

**Issue by XaviTorello** [BlackArch/blackarch#1806]
Canari integration seems to be broken.

When the main script is executed, there are some unmatched Python dependencies:

```  
$ /usr/bin/canari
Traceback (most recent call last):
  File "/usr/bin/canari", line 7, in <module>
    from canari.commands import *
  File "/usr/lib/python2.7/site-packages/canari/commands/create_package.py", line 5, in <module>
    from mrbob.configurator import Configurator
ImportError: No module named mrbob.configurator
``` 
Once solved, appears the latest one:
```
Traceback (most recent call last):
  File "/usr/bin/canari", line 7, in <module>
    from canari.commands import *
  File "/usr/lib/python2.7/site-packages/canari/commands/create_profile.py", line 6, in <module>
    from canari.pkgutils.transform import TransformDistribution
  File "/usr/lib/python2.7/site-packages/canari/pkgutils/transform.py", line 9, in <module>
    from canari.pkgutils.maltego import MaltegoDistribution, MtzDistribution
  File "/usr/lib/python2.7/site-packages/canari/pkgutils/maltego.py", line 10, in <module>
    from safedexml import Model
ImportError: No module named safedexml
``` 

Please, review it and provide a fix.

**Comment by XaviTorello** [comment]
Temporal workaround, install py2 dependecies manually through PyPi:
- mr.bob
- safedexml

```
$ pip2 install mr.bob safedexml
``` 

Ensure that pip2 is used, by default pip points to pip3 and will deploy those depts for the Python 3 scope //Canari use Python2 without any virtualenv
