### ISSUE TITLE
Claripy/Z3 Broken

### ISSUE THREAD

**Issue by nbulischeck** [BlackArch/blackarch#1862]
When testing out [angr](angr.io), I ran into an issue with Claripy/Z3. If this isn't something fixable, feel free to close this.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/angr/__init__.py", line 7, in <module>
    from .project import *
  File "/usr/lib/python2.7/site-packages/angr/project.py", line 10, in <module>
    import cle
  File "/usr/lib/python2.7/site-packages/cle/__init__.py", line 12, in <module>
    from .loader import *
  File "/usr/lib/python2.7/site-packages/cle/loader.py", line 9, in <module>
    import claripy
  File "/usr/lib/python2.7/site-packages/claripy/__init__.py", line 16, in <module>
    from . import backends as _backends_module
  File "/usr/lib/python2.7/site-packages/claripy/backends/__init__.py", line 715, in <module>
    from .backend_z3 import BackendZ3
  File "/usr/lib/python2.7/site-packages/claripy/backends/backend_z3.py", line 64, in <module>
    z3.init(z3_path)
AttributeError: 'module' object has no attribute 'init'
```

# Steps to Reproduce
Fresh install of Arch
./strap.sh
pacman -S angr
python2 -c 'import angr'

**Comment by NovaCygni** [comment]
Requires this version of Claripy to be installed, please change PKGBUILD as required and ideally add a linky in our BA repos. https://github.com/angr/claripy
works :)
