### ISSUE TITLE
wifiphisher broken 

### ISSUE THREAD

**Issue by gh00sty** [BlackArch/blackarch#1884]
➜  ~ wifiphisher 
Traceback (most recent call last):
  File "/usr/bin/wifiphisher", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3195, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3179, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3208, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 681, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 999, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 885, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'roguehostapd' distribution was not found and is required by wifiphisher

➜  ~ pacman -Ss roguehostapd
blackarch/python2-roguehostapd 1.1.6-1 [installed]
    Hostapd wrapper for hostapd.

➜  ~ pacman -Ss wifiphisher
blackarch/wifiphisher 651.62ebce8-1 (blackarch blackarch-wireless blackarch-social) [installed]
    Fast automated phishing attacks against WPA networks.

**Comment by NovaCygni** [comment]
The fix is right here https://github.com/wifiphisher/wifiphisher/pull/880/files
As I state in the BR for this issue on his Repo, WTF with the idiotic checks in the first place :/

**Comment by noptrix** [comment]
should be fixed now
