### ISSUE TITLE
WhatWeb wrapper is lacking shebang

### ISSUE THREAD

**Issue by bcoles** [BlackArch/blackarch#1941]
This issue was reported to WhatWeb: https://github.com/urbanadventurer/WhatWeb/issues/256

I haven't tested this issue, however, reportedly BlackArch attempts to execute WhatWeb as python.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shl/Github/webhackshl/modules/fingerwebmod.py", line 39, in whatw
    call(["whatweb","-v", web])
  File "/usr/lib/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: 'whatweb'
```

Taking a look at the [build script](https://github.com/BlackArch/blackarch/blob/master/packages/whatweb/PKGBUILD) shows the `/usr/bin/whatweb` wrapper is constructed as follows:

```bash
  cat > "$pkgdir/usr/bin/whatweb" << EOF
cd /usr/share/whatweb
exec ruby whatweb "\${@}"
EOF
```

Fixing this is possibly as simple as prefacing the executable wrapper with `#!/bin/bash`.

**Comment by noptrix** [comment]
@bcoles thanks for reporting. this has been fixed now.
