### ISSUE TITLE
Unable to satisfy dependency 'packer-io' required by malboxes

### ISSUE THREAD

**Issue by Edu4rdSHL** [BlackArch/blackarch#2004]
There are a issue in the malboxes PKGBUILD, [this line](https://github.com/BlackArch/blackarch/blob/2cb396641b969fcf84284e6ed16f65032d9f3f96/packages/malboxes/PKGBUILD#L12) have **packer-io** as dependency but **packer-io** is not in the repos.

```
 ➤➤➤➤ ▶ sudo pacman -S malboxes 
resolving dependencies...
warning: cannot resolve "packer-io", a dependency of "malboxes"
:: The following package cannot be upgraded due to unresolvable dependencies:
      malboxes
```

**Comment by Edu4rdSHL** [comment]
Changing **packer-io** for **packer** seems to solve the initial issue, anyways, a new issue is reproducible:
```

 ➤➤➤➤ ▶ malboxes
Traceback (most recent call last):
  File "/usr/bin/malboxes", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3105, in <module>
    @_call_aside
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3089, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3118, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 578, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 895, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 781, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'Jinja2' distribution was not found and is required by malboxes
```
Adding **python-jinja** as dependency solve that.
