### ISSUE TITLE
voltron error

### ISSUE THREAD

**Issue by GasparVardanyan** [BlackArch/blackarch#2027]
[ GasparVardanyan ~ ]$ voltron 
Traceback (most recent call last):
  File "/sbin/voltron", line 11, in <module>
    load_entry_point('voltron==0.1.7', 'console_scripts', 'voltron')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2707, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2325, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2331, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/voltron/__init__.py", line 95, in <module>
    setup_env()
  File "/usr/lib/python3.7/site-packages/voltron/__init__.py", line 31, in setup_env
    pkg_plugins=PluginDirectory('plugins', parent=PackageDirectory())
  File "/usr/lib/python3.7/site-packages/scruffy/env.py", line 47, in __init__
    self.add(**kwargs)
  File "/usr/lib/python3.7/site-packages/scruffy/env.py", line 112, in add
    self._children[key].prepare()
  File "/usr/lib/python3.7/site-packages/scruffy/file.py", line 437, in prepare
    self.load()
  File "/usr/lib/python3.7/site-packages/scruffy/file.py", line 443, in load
    self._pm.load_plugins(self.path)
  File "/usr/lib/python3.7/site-packages/scruffy/plugin.py", line 65, in load_plugins
    self.load_plugins(filepath)
  File "/usr/lib/python3.7/site-packages/scruffy/plugin.py", line 61, in load_plugins
    mod = imp.load_module(modname, file, path, descr)
  File "/usr/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "/usr/lib/python3.7/site-packages/voltron/plugins/debugger/dbg_gdb.py", line 663, in <module>
    class GDBCommand(DebuggerCommand, gdb.Command):
AttributeError: module 'gdb' has no attribute 'Command'
[ GasparVardanyan ~ ]$

**Comment by GasparVardanyan** [comment]
[ GasparVardanyan ~ ]$ voltron 
Traceback (most recent call last):
  File "/sbin/voltron", line 11, in <module>
    load_entry_point('voltron==0.1.7', 'console_scripts', 'voltron')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2714, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/voltron/__init__.py", line 95, in <module>
    setup_env()
  File "/usr/lib/python3.7/site-packages/voltron/__init__.py", line 31, in setup_env
    pkg_plugins=PluginDirectory('plugins', parent=PackageDirectory())
  File "/usr/lib/python3.7/site-packages/scruffy/env.py", line 47, in __init__
    self.add(**kwargs)
  File "/usr/lib/python3.7/site-packages/scruffy/env.py", line 112, in add
    self._children[key].prepare()
  File "/usr/lib/python3.7/site-packages/scruffy/file.py", line 437, in prepare
    self.load()
  File "/usr/lib/python3.7/site-packages/scruffy/file.py", line 443, in load
    self._pm.load_plugins(self.path)
  File "/usr/lib/python3.7/site-packages/scruffy/plugin.py", line 65, in load_plugins
    self.load_plugins(filepath)
  File "/usr/lib/python3.7/site-packages/scruffy/plugin.py", line 61, in load_plugins
    mod = imp.load_module(modname, file, path, descr)
  File "/usr/lib/python3.7/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "/usr/lib/python3.7/site-packages/voltron/plugins/view/memory.py", line 16
    async = True
          ^
SyntaxError: invalid syntax
[ GasparVardanyan ~ ]$
