### ISSUE TITLE
onionshare-gui error

### ISSUE THREAD

**Issue by GasparVardanyan** [BlackArch/blackarch#2028]
[ GasparVardanyan ~ ]$ onionshare-gui 
Traceback (most recent call last):
  File "/sbin/onionshare-gui", line 21, in <module>
    import onionshare_gui
  File "/usr/lib/python2.7/site-packages/onionshare_gui/__init__.py", line 25, in <module>
    from onionshare import strings
  File "/usr/lib/python2.7/site-packages/onionshare/__init__.py", line 25, in <module>
    from .web import Web
  File "/usr/lib/python2.7/site-packages/onionshare/web.py", line 618
    print('{} - {}     '.format(self.web.common.human_readable_filesize(self.onionshare_progress[filename]), filename), end='\r')
                                                                                                                           ^
SyntaxError: invalid syntax
[ GasparVardanyan ~ ]$

**Comment by noptrix** [comment]
fixed with #2031
