### ISSUE TITLE
Arduino IDE crash issue

### ISSUE THREAD

**Issue by n0tty** [BlackArch/blackarch#2088]
On running Arduino IDE, the following error seems to come
```
[ EDT18053 deadfeed ]# arduino
Picked up JAVA_TOOL_OPTIONS: 
/usr/share/gtk-2.0/gtkrc:55: Murrine configuration option "scrollbar_color" is no longer supported and will be ignored.
java.lang.NullPointerException
	at processing.app.BaseNoGui.onBoardOrPortChange(BaseNoGui.java:679)
	at processing.app.Base.onBoardOrPortChange(Base.java:1313)
	at processing.app.Base.<init>(Base.java:276)
	at processing.app.Base.main(Base.java:145)

```
This seems to crash arduino ide.

**Comment by n0tty** [comment]
The fix for this is to install arduino-avr-core
`pacman -Sy arduino-avr-core`

**Comment by n0tty** [comment]
The fix for this is to install arduino-avr-core
`pacman -Sy arduino-avr-core`
