### ISSUE TITLE
Deblaze source host is dead

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2127]
deblaze source website is dead

https://github.com/BlackArch/blackarch/blob/36ea04caaa433b93a9117107fd5b42c252871969/packages/deblaze/PKGBUILD#L1-L31

`http://deblaze-tool.appspot.com/` is giving http 404 now, there is an archive of the website here archive.is/deblaze-tool.appspot.com and I found this source code https://github.com/SpiderLabs/deblaze

Is the package source stored on blackarch repo ? Because the package is still installable through Blackarch ...

```
$ sudo pacman -Si deblaze                         
Repository      : blackarch
Name            : deblaze
Version         : 0.3-5
Description     : A remote method enumeration tool for flex servers
Architecture    : any
URL             : http://deblaze-tool.appspot.com/
Licenses        : GPL3
Groups          : blackarch  blackarch-scanner
Provides        : None
Depends On      : python2  python2-pillow
Optional Deps   : None
Conflicts With  : None
Replaces        : None
Download Size   : 1745,52 KiB
Installed Size  : 9893,00 KiB
Packager        : Evan Teitelman <teitelmanevan@gmail.com>
Build Date      : sam. 22 mars 2014 13:35:48 CET
Validated By    : MD5 Sum  SHA-256 Sum  Signature

$ sudo pacman -S deblaze                          
resolving dependencies...
looking for conflicting packages...

Packages (1) deblaze-0.3-5

Total Installed Size:  9,66 MiB
Net Upgrade Size:      0,00 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                                                                                 [############################################################################] 100%
(1/1) checking package integrity                                                                                               [############################################################################] 100%
(1/1) loading package files                                                                                                    [############################################################################] 100%
(1/1) checking for file conflicts                                                                                              [############################################################################] 100%
(1/1) checking available disk space                                                                                            [############################################################################] 100%
:: Processing package changes...
(1/1) reinstalling deblaze                                                                                                     [############################################################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
```

... but not manually (of course because source host is dead):

```
$ makepkg -si
==> Making package: deblaze 0.3-6 (mar. 20 nov. 2018 16:40:57 CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading download...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
==> ERROR: Failure while downloading http://deblaze-tool.appspot.com/download
    Aborting...
```

So we need to re-do a PKGBUILD using the github but IDK if the version on github is the last one.

**Comment by noraj** [comment]
looking at kali deblaze package, it seems they use the git repo I mentioned: https://tools.kali.org/web-applications/deblaze, http://git.kali.org/gitweb/?p=packages/deblaze.git;a=summary

**Comment by noraj** [comment]
Also after installation the Image module is not satisfied:

```python
Traceback (most recent call last):
  File "deblaze-0.3.py", line 35, in <module>
    import swfdecompiler
  File "/usr/share/deblaze/swfdecompiler.py", line 24, in <module>
    from outputManager import outputManager
  File "/usr/share/deblaze/outputManager.py", line 23, in <module>
    import Image
ImportError: No module named Image
```
