### ISSUE TITLE
Wascan dependency issue

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2131]
Wascan rely on beautifulsoup (bs) but between beautifulsoup version 3 and for the import method is not the same.

Right now wascan onlt try to import bs3 but only bs4 is in offficial arch repos.
So I made a PR on wascan project https://github.com/m4ll0k/WAScan/pull/61

Alternativelly a user can use python2-beautifulsoup3 instead of python2-beautifulsoup4 [from AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python2-beautifulsoup3) or [from blackarch repo](https://github.com/BlackArch/blackarch/blob/master/packages/python2-beautifulsoup3/PKGBUILD).

We won't change wascan PKGBUILD as this is more a wascan code fix.

I made this issue to trace this and to allow people to find leads on how to resolve this problem:

```python
Traceback (most recent call last):                                                                                                                   
  File "wascan.py", line 37, in <module>                                                                                                             
    from lib.handler.crawler import *                                                                                                                
  File "/usr/share/wascan/lib/handler/crawler.py", line 10, in <module>                                                                              
    from lib.request.crawler import SCrawler                                                                                                         
  File "/usr/share/wascan/lib/request/crawler.py", line 15, in <module>                                                                              
    from BeautifulSoup import BeautifulSoup                                                                                                          
ImportError: No module named BeautifulSoup
```

https://github.com/BlackArch/blackarch/blob/master/packages/wascan/PKGBUILD

**Comment by Edu4rdSHL** [comment]
Please report it to https://github.com/m4ll0k/WAScan only and wait to the tool update.

**Comment by noraj** [comment]
@Edu4rdSHL My fix was merged on WASCan project, you can reopen the issue here.

**Comment by Edu4rdSHL** [comment]
Please, tell the developer to release a new version with those fixes and I'll bump the package version.

**Comment by noraj** [comment]
Tracking https://github.com/m4ll0k/WAScan/issues/63

**Comment by Edu4rdSHL** [comment]
Ok, thank you. Please let me know when the release are available to bump the package.
