### ISSUE TITLE
[dnsrecon]: missing dependencies

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2322]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

Missing dependencies.

### Steps to reproduce

```
sudo pacman -S dnsrecon 
[sudo] password for noraj: 
Sorry, try again.
[sudo] password for noraj: 
resolving dependencies...
looking for conflicting packages...

Packages (2) python-dnspython-1.16.0-1  dnsrecon-2:0.9.0-1

Total Download Size:   0,64 MiB
Total Installed Size:  2,72 MiB

:: Proceed with installation? [Y/n] y
:: Retrieving packages...
 python-dnspython-1.16.0-1-any                                                                                                            191,8 KiB   160K/s 00:01 [#####################################################################################################] 100%
 dnsrecon-2:0.9.0-1-any                                                                                                                   461,9 KiB   796K/s 00:01 [#####################################################################################################] 100%
(2/2) checking keys in keyring                                                                                                                                     [#####################################################################################################] 100%
(2/2) checking package integrity                                                                                                                                   [#####################################################################################################] 100%
(2/2) loading package files                                                                                                                                        [#####################################################################################################] 100%
(2/2) checking for file conflicts                                                                                                                                  [#####################################################################################################] 100%
(2/2) checking available disk space                                                                                                                                [#####################################################################################################] 100%
:: Processing package changes...
(1/2) installing python-dnspython                                                                                                                                  [#####################################################################################################] 100%
Optional dependencies for python-dnspython
    python-ecdsa: DNSSEC support
    python-pycryptodome: DNSSEC support [installed]
    python-idna: support for updated IDNA 2008 [installed]
(2/2) installing dnsrecon                                                                                                                                          [#####################################################################################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...

dnsrecon -d example.com -t axfr
Traceback (most recent call last):
  File "dnsrecon.py", line 67, in <module>
    from lib.crtenum import scrape_crtsh
  File "/usr/share/dnsrecon/lib/crtenum.py", line 20, in <module>
    from lxml import etree
ModuleNotFoundError: No module named 'lxml'
```
### Solution

#2323

**Comment by Edu4rdSHL** [comment]
PR merged.
