### ISSUE TITLE
python-plotly upgrade breaks theHarvester

### ISSUE THREAD

**Issue by Hritik14** [BlackArch/blackarch#2473]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description
The plotly.plotly module is deprecated, and the current version of theHarvester uses it. 

### Steps to reproduce
run `theHarvester` 

**Actual result:** 
```
Traceback (most recent call last):
  File "/usr/bin/theharvester", line 5, in <module>
    from theHarvester import __main__
  File "/usr/share/theharvester/theHarvester/__main__.py", line 7, in <module>
    from theHarvester.lib import reportgraph
  File "/usr/share/theharvester/theHarvester/lib/reportgraph.py", line 5, in <module>
    import plotly.plotly as py
  File "/usr/lib/python3.7/site-packages/plotly/plotly/__init__.py", line 4, in <module>
    _chart_studio_error("plotly")
  File "/usr/lib/python3.7/site-packages/_plotly_future_/__init__.py", line 49, in _chart_studio_error
    submodule=submodule
ImportError: 
The plotly.plotly module is deprecated,
please install the chart-studio package and use the
chart_studio.plotly module instead. 
```
**Expected result:**
theHarvester should launch

### Info for developers

**Tool version:** 730.165d691-1

**Comment by noraj** [comment]
I rather have

```
Traceback (most recent call last):
  File "/usr/bin/theharvester", line 11, in <module>
    load_entry_point('theHarvester==3.1.0.dev2', 'console_scripts', 'theHarvester')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/theHarvester/__main__.py", line 5, in <module>
    from theHarvester.lib import hostchecker
  File "/usr/lib/python3.7/site-packages/theHarvester/lib/hostchecker.py", line 8, in <module>
    import aiodns
ModuleNotFoundError: No module named 'aiodns'
```

**Comment by noraj** [comment]
Reproduced in sandbox environment.

```
blackarch-devtools -t -e theharvester -p ./theharvester-1051.2711882-1-any.pkg.tar.xz
loading packages...
warning: theharvester-1051.2711882-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Packages (1) theharvester-1051.2711882-1

Total Installed Size:  2,67 MiB
Net Upgrade Size:      0,00 MiB

:: Proceed with installation? [Y/n] 
(1/1) checking keys in keyring                                                                                                                 [########################################################################################] 100%
(1/1) checking package integrity                                                                                                               [########################################################################################] 100%
(1/1) loading package files                                                                                                                    [########################################################################################] 100%
(1/1) checking for file conflicts                                                                                                              [########################################################################################] 100%
(1/1) checking available disk space                                                                                                            [########################################################################################] 100%
:: Processing package changes...
(1/1) reinstalling theharvester                                                                                                                [########################################################################################] 100%
:: Running post-transaction hooks...
(1/1) Arming ConditionNeedsUpdate...
Package ./theharvester-1051.2711882-1-any.pkg.tar.xz installed correctly! Testing it now...
Traceback (most recent call last):
  File "/usr/bin/theharvester", line 11, in <module>
    load_entry_point('theHarvester==3.1.0.dev2', 'console_scripts', 'theHarvester')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/theHarvester/__main__.py", line 5, in <module>
    from theHarvester.lib import hostchecker
  File "/usr/lib/python3.7/site-packages/theHarvester/lib/hostchecker.py", line 8, in <module>
    import aiodns
ModuleNotFoundError: No module named 'aiodns'
```
