### ISSUE TITLE
mobsf: config error

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2510]
does no launch anymore after last update

```
$ mobsf          
[2019-10-28 14:25:43 +0100] [13449] [INFO] Starting gunicorn 19.9.0
[2019-10-28 14:25:43 +0100] [13449] [INFO] Listening at: http://0.0.0.0:8000 (13449)
[2019-10-28 14:25:43 +0100] [13449] [INFO] Using worker: threads
[2019-10-28 14:25:43 +0100] [13453] [INFO] Booting worker with pid: 13453
[2019-10-28 13:25:43 +0000] [13453] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/config.py", line 562, in configure
    handler = self.configure_handler(handlers[name])
  File "/usr/lib/python3.7/logging/config.py", line 735, in configure_handler
    result = factory(**kwargs)
  File "/usr/lib/python3.7/logging/__init__.py", line 1087, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.7/logging/__init__.py", line 1116, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
PermissionError: [Errno 13] Permission denied: '/usr/share/mobsf/logs/debug.log'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/lib/python3.7/site-packages/gunicorn/workers/gthread.py", line 104, in init_process
    super(ThreadWorker, self).init_process()
  File "/usr/lib/python3.7/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/lib/python3.7/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/lib/python3.7/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/usr/share/mobsf/MobSF/wsgi.py", line 17, in <module>
    application = WhiteNoise(get_wsgi_application(),
  File "/usr/lib/python3.7/site-packages/django/core/wsgi.py", line 12, in get_wsgi_application
    django.setup(set_prefix=False)
  File "/usr/lib/python3.7/site-packages/django/__init__.py", line 19, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "/usr/lib/python3.7/site-packages/django/utils/log.py", line 76, in configure_logging
    logging_config_func(logging_settings)
  File "/usr/lib/python3.7/logging/config.py", line 799, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.7/logging/config.py", line 570, in configure
    '%r' % name) from e
ValueError: Unable to configure handler 'logfile'
[2019-10-28 13:25:43 +0000] [13453] [INFO] Worker exiting (pid: 13453)
[2019-10-28 14:25:43 +0100] [13449] [INFO] Shutting down: Master
[2019-10-28 14:25:43 +0100] [13449] [INFO] Reason: Worker failed to boot.
```

**Comment by noraj** [comment]
It won't run if it has not the permission to write into `/usr/share/mobsf/logs/debug.log`. The dirty workaround is to launch it as root.

**Comment by noraj** [comment]
I think we can apply a patch to change this line in `MobSF/settings.py`:

```
384             'filename': os.path.join(MobSF_HOME, 'logs', 'debug.log'),                                                                                                                                                                                                      
```

**Comment by aancw** [comment]
@noraj I'm using mobsf from git repo instead and it works with local folder.
```
↳ cat MobSF/settings.py| grep logs
LOG_DIR = os.path.join(MobSF_HOME, 'logs/')
            'filename': os.path.join(MobSF_HOME, 'logs', 'debug.log'),
```
I think logs file is created under the mobsf current dir project as mentioned in PKGBUILD and install script

```
↳ cat MobSF/settings.py| grep MobSF_HOME
MobSF_HOME = get_mobsf_home(USE_HOME)
LOG_DIR = os.path.join(MobSF_HOME, 'logs/')
DWD_DIR = os.path.join(MobSF_HOME, 'downloads/')
SCREEN_DIR = os.path.join(MobSF_HOME, 'downloads/screen/')
UPLD_DIR = os.path.join(MobSF_HOME, 'uploads/')
DB_DIR = os.path.join(MobSF_HOME, 'db.sqlite3')
SECRET_FILE = os.path.join(MobSF_HOME, 'secret')
        USER_CONFIG = os.path.join(MobSF_HOME, 'config.py')
SECRET_KEY = first_run(SECRET_FILE, BASE_DIR, MobSF_HOME)
            'filename': os.path.join(MobSF_HOME, 'logs', 'debug.log'),

↳ grep -r "get_mobsf_home" Mobile-Security-Framework-MobSF 
Mobile-Security-Framework-MobSF/MobSF/utils.py:def get_mobsf_home(use_home):
Mobile-Security-Framework-MobSF/MobSF/settings.py:                         get_mobsf_home)
Mobile-Security-Framework-MobSF/MobSF/settings.py:MobSF_HOME = get_mobsf_home(USE_HOME)



def get_mobsf_home(use_home):
    try:
        mobsf_home = ''
        if use_home:
            mobsf_home = os.path.join(os.path.expanduser('~'), '.MobSF')
            # MobSF Home Directory
            if not os.path.exists(mobsf_home):
                os.makedirs(mobsf_home)
            create_user_conf(mobsf_home)
        else:
```
Change the installation folder if want to run mobsf as normal user. CMIIW

**Comment by noraj** [comment]
@aancw No changing the installation directory is not an option, the installation directory is standardized.

`debug.log` should be written to the current/working directory or in a user directory not in the install directory.

But downloads, uploads, all logs, db index should be stored in a user directory too.

In fact the change will be super easy as there is an option for that.

```
USE_HOME = False

# True : All Uploads/Downloads will be stored in user's home directory
# False : All Uploads/Downloads will be stored in MobSF root directory
# If you need multiple users to share the scan results set this to False
```

https://github.com/MobSF/Mobile-Security-Framework-MobSF/wiki/5.-Home-Directory-Support

## TODOLIST:

- [ ] patch `MobSF/settings.py` to sue user directory: `USE_HOME = True`

I'll do some test and do that.

**Comment by aancw** [comment]
Nice. I didn't see that option. Better to use home dir if root privileges is considered.
