### ISSUE TITLE
pip broken on fresh arch install 

### ISSUE THREAD

**Issue by Danhyal-Masood** [BlackArch/blackarch#2583]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description
PIp breaks on a fresh install of blackarch

### Steps to reproduce
- install arch
- install blackarch with pacman -S blackarch
- broken pip :(

terminal output after running pip3 (pip2 is unaffected)
```
[danhyal@archlinux ~]$ pip3
Traceback (most recent call last):
  File "/usr/bin/pip3", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws = cls()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 567, in __init__
    self.add_entry(entry)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 623, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2065, in find_on_path
    for dist in factory(fullpath):
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2134, in distributions_from_metadata
    yield Distribution.from_location(
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2590, in from_location
    return cls(
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2994, in _reload_version
    md_version = self._get_version()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2772, in _get_version
    version = _version_from_file(lines)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2556, in _version_from_file
    line = next(iter(version_lines), '')
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2767, in _get_metadata
    for line in self.get_metadata_lines(name):
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1432, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1420, in get_metadata
    value = self._get(path)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1617, in _get
    return stream.read()
OSError: [Errno 5] Input/output error

```

**Comment by Edu4rdSHL** [comment]
Hello, @Danhyal-Masood. We doesn't touch anything of `pip` or their dependencies. Are you connected using SSH?

**Comment by Danhyal-Masood** [comment]
> Hello, @Danhyal-Masood. We doesn't touch anything of `pip` or their dependencies. Are you connected using SSH?

Nope, It must be related to one of the python3 packages you recently updated, this didnt happen a few days ago

**Comment by Edu4rdSHL** [comment]
The error occurs because pip doesn't have where to show the information (stdout), so, it's a system/terminal issue instead of our issue.

Closing because it's unrelated to us. Try changing the terminal or rebooting the OS, I've a full updated BlackArch system without that issue.

**Comment by noraj** [comment]
General advices : 

- reboot after an upgrade
- never use pip outside a virtualenv
