### ISSUE TITLE
Yawast: dependencies are broken

### ISSUE THREAD

**Issue by Hax0rG1rl** [BlackArch/blackarch#2585]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description
Yawast does not work as intended after upgrade. 

### Steps to reproduce
- upgrade to the latest version
- try to launch yawast

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

```
yawast target_1
Traceback (most recent call last):
  File "/sbin/yawast", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'vistir' distribution was not found and is required by yawast

```

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

I was expected the tool to work. 

### Screenshots

![image](https://user-images.githubusercontent.com/3704868/71553632-d3bbda80-2a77-11ea-8e8b-5203cf025c89.png)

**Comment by noraj** [comment]
We should take a look at https://github.com/adamcaudill/yawast/blob/master/requirements.txt changes to update https://github.com/BlackArch/blackarch/blob/master/packages/yawast/PKGBUILD

**Comment by noptrix** [comment]
@Hax0rG1rl thank you! @noraj yes, i will do that now.
