### ISSUE TITLE
packerid: ValueError: invalid literal for int() with base 16: 'V3'

### ISSUE THREAD

**Issue by vdun** [BlackArch/blackarch#2620]
```
# packerid test.exe
Traceback (most recent call last):
  File "/usr/bin/packerid", line 58, in <module>
    signatures = peutils.SignatureDatabase('/usr/share/packerid/userdb.txt')
  File "/usr/lib/python2.7/site-packages/peutils.py", line 76, in __init__
    self.__load(filename=filename, data=data)
  File "/usr/lib/python2.7/site-packages/peutils.py", line 443, in __load
    signature_bytes = [to_byte(b) for b in signature.split()]
  File "/usr/lib/python2.7/site-packages/peutils.py", line 427, in to_byte
    return int(value, 16)
ValueError: invalid literal for int() with base 16: 'V3'
```

**Comment by noraj** [comment]
Seems like an upstream issue https://github.com/sooshie/packerid/issues/7

**Comment by noraj** [comment]
Upstream was not updated maintained for 4 years+.

```
$ ba-dev -b                                                                                               
Syncing chroot copy /home/noraj/blackarch_chroot/blackarch/ with /home/noraj/blackarch_chroot/root/ ...
Chroot environment is ready!
==> Making package: packerid 1.4-7 (lun. 03 févr. 2020 23:06:59 CET)
==> Retrieving sources...
  -> Downloading packerid.py...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   169  100   169    0     0    481      0 --:--:-- --:--:-- --:--:--   480
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
curl: (22) The requested URL returned error: 404 Not Found
==> ERROR: Failure while downloading http://handlers.sans.org/jclausing/packerid.py
    Aborting...
==> ERROR: Could not download sources.
Failed to build the package
```

The source URL is dead and maybe updated to https://github.com/sooshie/packerid/ (see #2494) even before trying to investigate.
But since the tool uses the deprecated python 2 + is not maintained, I don't know if it's even worth it.

@noptrix What do you think? We remove the package or update the PKGBUILD to the previously linked github repo + try to fix the upstream code?
