### ISSUE TITLE
Broken package monitoring

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2759]
[broken packages](https://github.com/BlackArch/blackarch/blob/master/lists/broken) reason

- [ ] aimage: `configure: error: OpenSSL library 'libssl-dev' not installed; cannot continue.`
- [ ] amoco: #2760
- [ ] autopwn: upstream https://github.com/nccgroup/autopwn/issues/14
- [ ] aws-extender-cli & python-boto https://github.com/BlackArch/blackarch/issues/4141

**Comment by aancw** [comment]
[] birp: downgrade python2-py3270 to 0.3.4

```
 △ ~ sudo pacman -S birp
resolving dependencies...
looking for conflicting packages...

Packages (3) python2-py3270-0.3.5-4  x3270-1:3.6ga8-1  birp-65.b2e108a-1

 ▲ ~ python2                                                                                                                                                                                                                                                                 23s
Python 2.7.18 (default, Apr 23 2020, 22:32:06)
[GCC 9.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from py3270 import x3270App
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name x3270App

 ▲ ~ sudo pacman -Rns python2-py3270                                                                                                                                                                                                                                          9s
checking dependencies...
error: failed to prepare transaction (could not satisfy dependencies)
:: removing python2-py3270 breaks dependency 'python2-py3270' required by birp


 ▲ ~ python2                                                                                                                                                                                                                                                                 10s
Python 2.7.18 (default, Apr 23 2020, 22:32:06)
[GCC 9.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from py3270 import x3270App
>>>
```

**Comment by noptrix** [comment]
> * [x]   birp: downgrade python2-py3270 to 0.3.4
> 
> ```
>  △ ~ sudo pacman -S birp
> resolving dependencies...
> looking for conflicting packages...
> 
> Packages (3) python2-py3270-0.3.5-4  x3270-1:3.6ga8-1  birp-65.b2e108a-1
> 
>  ▲ ~ python2                                                                                                                                                                                                                                                                 23s
> Python 2.7.18 (default, Apr 23 2020, 22:32:06)
> [GCC 9.3.0] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from py3270 import x3270App
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> ImportError: cannot import name x3270App
> 
>  ▲ ~ sudo pacman -Rns python2-py3270                                                                                                                                                                                                                                          9s
> checking dependencies...
> error: failed to prepare transaction (could not satisfy dependencies)
> :: removing python2-py3270 breaks dependency 'python2-py3270' required by birp
> 
> 
>  ▲ ~ python2                                                                                                                                                                                                                                                                 10s
> Python 2.7.18 (default, Apr 23 2020, 22:32:06)
> [GCC 9.3.0] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from py3270 import x3270App
> >>>
> ```

i've done this with: https://github.com/BlackArch/blackarch/commit/64a7b79c4c66935b2ed45f554f5b395f7901f539  and https://github.com/BlackArch/blackarch/commit/16dbf2f543a1d8b561010ae33ba2bd6323ca7df7

**Comment by aancw** [comment]
- [ ] grr: Need shared library libgflags.so.2
Workaround fix : Symlink libgflags.so.2.2 to libgflags.so.2
https://www.archlinux.org/packages/community/x86_64/gflags/files/
```
 △ ~ grrshot --help
grrshot: error while loading shared libraries: libgflags.so.2: cannot open shared object file: No such file or directory

 △ ~ grrplay --help
grrplay: error while loading shared libraries: libgflags.so.2: cannot open shared object file: No such file or directory
```

**Comment by aancw** [comment]
- [ ] climber: Error ImportError: No module named resource

From upstream repo it say just clone master branch https://github.com/knipknap/exscript/issues/145 and I've saw that PKGBUILD did that.

**Comment by aancw** [comment]
- [ ] eapeak:    
```
from scapy.layers.l2 import EAP
ImportError: cannot import name EAP
```
From scapy docs, it's refactored from layers.l2 to layers.eap
https://scapy.readthedocs.io/en/latest/api/scapy.layers.eap.html

Ref: https://github.com/secdev/scapy/pull/725#issuecomment-318611764

**Comment by aancw** [comment]
- [ ] filebuster: 

```
Can't locate IO/Async/Timer/Periodic.pm in @INC (you may need to install the IO::Async::Timer::Periodic module) (@INC contains: /usr/lib/perl5/5.30/site_perl /usr/share/perl5/site_perl /usr/lib/perl5/5.30/vendor_perl /usr/share/perl5/vendor_perl /usr/lib/perl5/5.30/core_perl /usr/share/perl5/core_perl) at /usr/bin/filebuster line 35.
BEGIN failed--compilation aborted at /usr/bin/filebuster line 35.
```
We need to include `perl-io-async` in depends https://aur.archlinux.org/packages/perl-io-async/

https://github.com/BlackArch/blackarch/blob/16277fdcf8f58801f84d617afef1019d6be51395/packages/filebuster/PKGBUILD#L12

**Comment by ikstream** [comment]
- [ ] **malcom** 
```
$ malcom -c /usr/share/malcom/malcom.conf.example

===== Malcom 1.3a - Malware Communications Analyzer =====

{'MAX_WORKERS': '12', 'SKIP_TAGS': 'whitelisted', 'ACTIVATED': 'true'}
{'WEB': True, 'LISTEN_PORT': 8080, 'ANALYTICS': True, 'ACTIVATED': 'true', 'AUTH': False, 'MAX_WORKERS': 12, 'SKIP_TAGS': ['whitelisted'], 'VERSION': '1.3a', 'LISTEN_INTERFACE': '0.0.0.0'}
Detected interfaces:
[ERROR] [2020-06-22 19:56:25.941304] - Could not load GeoIP library - [Errno 2] No such file or directory: '/usr/share/malcom/Malcom/model/../auxiliary/geoIP/GeoIP2-City.mmdb'
Traceback (most recent call last):
  File "./malcom.py", line 77, in <module>
    from Malcom.sniffer import netsniffer
  File "/usr/share/malcom/Malcom/sniffer/netsniffer.py", line 16, in <module>
    from Malcom.model.model import Model
  File "/usr/share/malcom/Malcom/model/model.py", line 20, in <module>
    from Malcom.model.user_management import UserManager
  File "/usr/share/malcom/Malcom/model/user_management.py", line 14, in <module>
    from flask.ext.login import make_secure_token
ImportError: No module named ext.login
```

**Comment by ikstream** [comment]
> * [ ]  eapeak:
> 
> ```
> from scapy.layers.l2 import EAP
> ImportError: cannot import name EAP
> ```
> 
> From scapy docs, it's refactored from layers.l2 to layers.eap
> https://scapy.readthedocs.io/en/latest/api/scapy.layers.eap.html
> 
> Ref: [secdev/scapy#725 (comment)](https://github.com/secdev/scapy/pull/725#issuecomment-318611764)

There were two pull requests addressing this problem. [One](https://github.com/rsmusllp/eapeak/pull/6) was merged and later reverted as it seems to introduce some other issues. The maintainer recommended a rewrite in python 3, [but is not interessted (Feb 219)](https://github.com/rsmusllp/eapeak/pull/7) in doing so.
It received the last update in 2018. So it should be removed

**Comment by micwoj92** [comment]
I guess that bof-detector package is broken? I couldn't access the repo, it seems that the GitHub account was deleted.

**Comment by tylerstonge** [comment]
I'm having some issues with stegoveritas, seems similar to what's addressed here: #2751, but I'm running on a fresh Black Arch install and getting this issue.
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.9/site-packages/stegoveritas/modules/image/analysis/brute_lsb.py", line 13, in run_dump
    image.veritas.test_output(o)
  File "/usr/lib/python3.9/site-packages/stegoveritas/stegoveritas.py", line 79, in test_output
    m = magic.from_buffer(thing, mime=True)
AttributeError: module 'magic' has no attribute 'from_buffer'
```

**Comment by ikstream** [comment]
@tylerstonge please open an individual issue for this. I can't reproduce your issue right now, please provide

- which iso did you use to install and if you did an online install (if applicable)
- the package version of stegoveritas 
- the exact command you ran

**Comment by ikstream** [comment]
[ ] python-crc16
[ ] gr-gsm
[ ] python-port-for
[ ] python-pywebcopy
[x] python-sleekxmpp [#3335]

**Comment by noraj** [comment]
- [ ] `genisys`

Upstream `https://github.com/Cryptonian007/Genisys` was removed, seems that Cryptonian007 was a fork of https://github.com/noob-coder123/Genisys. But noob-coder123 (9 commits, v2.1) if far behind (Cryptonian007 was 53 commits, v2.5) so we have to choose a more up to date fork in https://github.com/noob-coder123/Genisys/network/members like https://github.com/ahayder/Genisys or https://github.com/baratt/Genisys that were up to date at that time. But those are dead forks, it doesn't seem to have any active fork.

**Comment by noraj** [comment]
- [x] pacu https://github.com/BlackArch/blackarch/pull/4627

Several dependencies are missing or out of date. Example:

```
➜ pacu               
Traceback (most recent call last):
  File "/usr/share/pacu/pacu/main.py", line 23, in <module>
    import jq  # type: ignore
    ^^^^^^^^^
<class 'ModuleNotFoundError'>: No module named 'jq'

Pacu was not able to start because a required Python package was not found.
Run `sh install.sh` to check and install Pacu's Python requirements.
```
