### ISSUE TITLE
[armitage] fails to connect to [metasploit] msfrpcd.

### ISSUE THREAD

**Issue by ghost** [BlackArch/blackarch#277]
Error message from `msfrpcd -U user -P pass`:

```
create_by_type': The address is already in use (0.0.0.0:55553). (Rex::AddressInUse)
    from /usr/share/metasploit/lib/rex/socket/comm/local.rb:192:in `create_by_type'
    from /usr/share/metasploit/lib/rex/socket/comm/local.rb:33:in `create'
    from /usr/share/metasploit/lib/rex/socket.rb:47:in `create_param'
    from /usr/share/metasploit/lib/rex/socket/tcp_server.rb:39:in `create_param'
    from /usr/share/metasploit/lib/rex/socket/tcp_server.rb:29:in `create'
    from /usr/share/metasploit/lib/rex/proto/http/server.rb:143:in `start'
    from /usr/share/metasploit/lib/rex/service_manager.rb:81:in `start'
    from /usr/share/metasploit/lib/rex/service_manager.rb:25:in `start'
    from /usr/share/metasploit/lib/msf/core/rpc/v10/service.rb:60:in `start'
    from /usr/share/metasploit/plugins/msgrpc.rb:97:in `run'
    from msfrpcd:112:in `<main>'
```

Error message from `armitage`:

```
[-] Metasploit Framework Exception: Login Failed
[lib/msf/core/rpc/v10/rpc_base.rb:16:in `error',
lib/msf/core/rpc/v10/rpc_auth.rb:37:in `rpc_login_noauth',
lib/msf/core/rpc/v10/service.rb:149:in `block in process',
lib/ruby/1.9.1/timeout.rb:69:in `timeout',
lib/msf/core/rpc/v10/service.rb:149:in `process',
lib/msf/core/rpc/v10/service.rb:89:in `on_request_uri',
lib/msf/core/rpc/v10/service.rb:71:in `block in start',
lib/rex/proto/http/handler/proc.rb:38:in `call',
lib/rex/proto/http/handler/proc.rb:38:in `on_request',
lib/rex/proto/http/server.rb:363:in `dispatch_request',
lib/rex/proto/http/server.rb:297:in `on_client_data',
lib/rex/proto/http/server.rb:157:in `block in start',
lib/rex/io/stream_server.rb:48:in `call', lib/rex/io/stream_server.rb:48:in
`on_client_data', lib/rex/io/stream_server.rb:192:in `block in
monitor_clients', lib/rex/io/stream_server.rb:190:in `each',
lib/rex/io/stream_server.rb:190:in `monitor_clients',
lib/rex/io/stream_server.rb:73:in `block in start',
lib/rex/thread_factory.rb:22:in `call', lib/rex/thread_factory.rb:22:in
`block in spawn', lib/msf/core/thread_manager.rb:100:in `call',
lib/msf/core/thread_manager.rb:100:in `block in spawn']
```

**Comment by All3xJ** [comment]
same thing here with archlinux.

**Comment by PedroSFreitas** [comment]
**Please don't necrobump.** Create a new issue, link to this one and provide more information (logs, verbose output, screenshot, everything that is relevant to help you).

Looking it.
