### ISSUE TITLE
malcom broken

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#2857]
@ikstream said in #2759

```
$ malcom -c /usr/share/malcom/malcom.conf.example

===== Malcom 1.3a - Malware Communications Analyzer =====

{'MAX_WORKERS': '12', 'SKIP_TAGS': 'whitelisted', 'ACTIVATED': 'true'}
{'WEB': True, 'LISTEN_PORT': 8080, 'ANALYTICS': True, 'ACTIVATED': 'true', 'AUTH': False, 'MAX_WORKERS': 12, 'SKIP_TAGS': ['whitelisted'], 'VERSION': '1.3a', 'LISTEN_INTERFACE': '0.0.0.0'}
Detected interfaces:
[ERROR] [2020-06-22 19:56:25.941304] - Could not load GeoIP library - [Errno 2] No such file or directory: '/usr/share/malcom/Malcom/model/../auxiliary/geoIP/GeoIP2-City.mmdb'
Traceback (most recent call last):
  File "./malcom.py", line 77, in <module>
    from Malcom.sniffer import netsniffer
  File "/usr/share/malcom/Malcom/sniffer/netsniffer.py", line 16, in <module>
    from Malcom.model.model import Model
  File "/usr/share/malcom/Malcom/model/model.py", line 20, in <module>
    from Malcom.model.user_management import UserManager
  File "/usr/share/malcom/Malcom/model/user_management.py", line 14, in <module>
    from flask.ext.login import make_secure_token
ImportError: No module named ext.login
```

Trying to reproduce 4 month later:

```
$ ba-dev -e 'malcom -c /usr/share/malcom/malcom.conf.example' -p malcom-708.02e55b9-2-any.pkg.tar.zst
...
Traceback (most recent call last):
  File "malcom.py", line 10, in <module>
    import netifaces as ni
ImportError: No module named netifaces
```

**Comment by noraj** [comment]
There is a python3 `python-netifaces` but not python2 package. Python2 is deprecated and the package is not maintained since 2017.

**Comment by Szewcson** [comment]
It also won't install since build dependency for obsolete openssl version.

```
  creating build/temp.linux-x86_64-2.7/src/cryptography/hazmat/bindings/__pycache__
  gcc -pthread -fno-strict-aliasing -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -DNDEBUG -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fPIC -I/usr/share/malcom/venv/include/python2.7 -c src/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_4ee21876x41fb9936.c -o build/temp.linux-x86_64-2.7/src/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_4ee21876x41fb9936.o
  src/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_4ee21876x41fb9936.c:364:5: error: conflicting types for ‘i2d_ASN1_OBJECT’; have ‘int(ASN1_OBJECT *, unsigned char **)’ {aka ‘int(struct asn1_object_st *, unsigned char **)’}
    364 | int i2d_ASN1_OBJECT(ASN1_OBJECT *, unsigned char **);
        |     ^~~~~~~~~~~~~~~
  In file included from src/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_4ee21876x41fb9936.c:197:
  /usr/include/openssl/asn1.h:530:5: note: previous declaration of ‘i2d_ASN1_OBJECT’ with type ‘int(const ASN1_OBJECT *, unsigned char **)’ {aka ‘int(const struct asn1_object_st *, unsigned char **)’}
    530 | int i2d_ASN1_OBJECT(const ASN1_OBJECT *a, unsigned char **pp);
        |     ^~~~~~~~~~~~~~~
  src/cryptography/hazmat/bindings/__pycache__/_Cryptography_cffi_4ee21876x41fb9936.c:372:5: error: conflicting types for ‘ASN1_STRING_type’; have ‘int(ASN1_STRING *)’ {aka ‘int(struct asn1_string_st *)’}
    372 | int ASN1_STRING_type(ASN1_STRING *);
        |     ^~~~~~~~~~~~~~~~
...
```
