### ISSUE TITLE
vmcloak: vmcloak.exceptions.CommandError

### ISSUE THREAD

**Issue by NedXD23** [BlackArch/blackarch#2980]
```
cuckoo@kali:~$ vmcloak init  --win7x64 win7x64base --cpus 2 --ramsize 2048 -v -d
DEBUG:vmcloak.abstract:Executing genisoimage: /usr/bin/genisoimage -quiet -b boot.img -o /home/cuckoo/.vmcloak/iso/win7x64base.iso -no-emul-boot -iso-level 2 -udf -J -l -D -N -joliet-long -relaxed-filenames -allow-limited-size /home/cuckoo/.vmcloak/iso/tmpEDNk49
DEBUG:vmcloak.vm:Running command: ['/usr/bin/VBoxManage', 'createvm', '--register', '--name', 'win7x64base', '--basefolder', '/home/cuckoo/.vmcloak/vms']
VBoxManage: error: Machine settings file '/home/cuckoo/.vmcloak/vms/win7x64base/win7x64base.vbox' already exists
VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component MachineWrap, interface IMachine, callee nsISupports
VBoxManage: error: Context: "CreateMachine(bstrSettingsFile.raw(), bstrName.raw(), ComSafeArrayAsInParam(groups), bstrOsTypeId.raw(), createFlags.raw(), machine.asOutParam())" at line 274 of file VBoxManageMisc.cpp
ERROR:vmcloak.vm:[-] Error running command: Command '['/usr/bin/VBoxManage', 'createvm', '--register', '--name', 'win7x64base', '--basefolder', '/home/cuckoo/.vmcloak/vms']' returned non-zero exit status 1
Traceback (most recent call last):
  File "/usr/local/bin/vmcloak", line 11, in <module>
    load_entry_point('VMCloak', 'console_scripts', 'vmcloak')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/cuckoo/.local/lib/python2.7/site-packages/vmcloak/main.py", line 258, in init
    m.create_vm()
  File "/home/cuckoo/.local/lib/python2.7/site-packages/vmcloak/vm.py", line 75, in create_vm
    basefolder=vms_path, register=True)
  File "/home/cuckoo/.local/lib/python2.7/site-packages/vmcloak/vm.py", line 41, in _call
    raise CommandError
vmcloak.exceptions.CommandError
```

**Comment by noraj** [comment]
Looks like an upstream issue to me and also vmcloak is using python 2.7 which is unsupported.

**Comment by andrie05** [comment]
How can i change Python version for vmcloak ?

**Comment by aancw** [comment]
@andrie05 You can't. It need refactoring from the upstream for python 3 compatibility.

**Comment by Edu4rdSHL** [comment]
The best approach to fix it package is switching to `venv`, the repo hasn't been updated since 2019, so I doubt it got fixed soon.

**Comment by D3vil0p3r** [comment]
https://github.com/BlackArch/blackarch/pull/4230 updated PKGBUILD for vmcloak Python3 by maintained fork of the original (abandoned) project. Please test it again by:
```
vmcloak -d init --win7x64 win7x64base --cpus 2 --ramsize 2048 vboxnet0
```
Currently I have an issue on attaching a network adapter to solve.

**Comment by D3vil0p3r** [comment]
https://github.com/BlackArch/blackarch/pull/4254

Waiting for an upstream issue ticket.
