### ISSUE TITLE
github-dorks missing python-deprecated dep

### ISSUE THREAD

**Issue by dualfade** [BlackArch/blackarch#3160]
github-dorks missing or broken python-deprecated.

[0] % GH_TOKEN=ghp_XXXXXXXXXXXXXXXXXXXXXXXXX github-dorks -u sanitized
Traceback (most recent call last):
  File "/usr/share/github-dorks/github-dork.py", line 4, in <module>
    import github3 as github
  File "/usr/lib/python3.9/site-packages/github3/__init__.py", line 24, in <module>
    from .api import (
  File "/usr/lib/python3.9/site-packages/github3/api.py", line 11, in <module>
    from .github import GitHub, GitHubEnterprise
  File "/usr/lib/python3.9/site-packages/github3/github.py", line 8, in <module>
    from . import apps
  File "/usr/lib/python3.9/site-packages/github3/apps.py", line 7, in <module>
    from jwcrypto import jwk
  File "/usr/lib/python3.9/site-packages/jwcrypto/jwk.py", line 14, in <module>
    from deprecated import deprecated
ModuleNotFoundError: No module named 'deprecated'

Will fix --
Assigning to myself.

**Comment by dualfade** [comment]
Something else is not quite right.. Looking into this --
