### ISSUE TITLE
Responder: python upgrade

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#3288]
It seems 2360981f8f7ff0b710fb3376ec390be46b4f89a3 wasn't enough to fix Responder after python 3.10 upgrade.

```
# responder -I tun0
Traceback (most recent call last):
  File "/usr/share/responder/odict.py", line 3, in <module>
    from UserDict import DictMixin
ModuleNotFoundError: No module named 'UserDict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/responder/Responder.py", line 359, in <module>
    main()
  File "/usr/share/responder/Responder.py", line 250, in main
    from poisoners.LLMNR import LLMNR
  File "/usr/share/responder/poisoners/LLMNR.py", line 18, in <module>
    import fingerprint
  File "/usr/share/responder/fingerprint.py", line 22, in <module>
    from packets import SMBHeader, SMBNego, SMBNegoFingerData, SMBSessionFingerData
  File "/usr/share/responder/packets.py", line 25, in <module>
    from odict import OrderedDict
  File "/usr/share/responder/odict.py", line 6, in <module>
    from collections import MutableMapping as DictMixin
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

**Comment by noraj** [comment]
Upstream tracking: https://github.com/lgandx/Responder/issues/172
