### ISSUE TITLE
runfinger python3 compatibility

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#3344]
### Bug description

[PKGBUILD](https://github.com/BlackArch/blackarch/blob/master/packages/responder/PKGBUILD)

```
$ responder-runfinger -i 10.0.0.0/24 -g
Traceback (most recent call last):
  File "/usr/share/responder/tools/odict.py", line 3, in <module>
    from UserDict import DictMixin
ModuleNotFoundError: No module named 'UserDict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/responder/tools/RunFinger.py", line 24, in <module>
    from RunFingerPackets import *
  File "/usr/share/responder/tools/RunFingerPackets.py", line 4, in <module>
    from odict import OrderedDict
  File "/usr/share/responder/tools/odict.py", line 6, in <module>
    from collections import MutableMapping as DictMixin
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
````

origin of the issue https://github.com/lgandx/Responder/blob/fd9bcf7de1816db2f3ca4c948d0de429cf66e9b6/tools/odict.py#L2-L6

```
$ python
Python 3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from collections import MutableMapping as DictMixin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'MutableMapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
```

https://stackoverflow.com/questions/70870041/cannot-import-name-mutablemapping-from-collections#answer-70870087

> Deprecated since version 3.3, will be removed in version 3.10: Moved [Collections Abstract Base Classes](https://docs.python.org/3.9/library/collections.abc.html#collections-abstract-base-classes) to the [collections.abc](https://docs.python.org/3.9/library/collections.abc.html#module-collections.abc) module. For backwards compatibility, they continue to be visible in this module through Python 3.9.
>
> Ref. https://docs.python.org/3.9/library/collections.html

**Comment by noraj** [comment]
upstream has been fixed

**Comment by noraj** [comment]
```
$ responder-runfinger -i 10.0.0.1
Traceback (most recent call last):
  File "/usr/share/responder/tools/RunFinger.py", line 72, in <module>
    cursor = sqlite3.connect(DB)
sqlite3.OperationalError: unable to open database file
```

`python RunFinger.py` from `/usr/share/responder/tools` or `python tools/RunFinger.py` from `/usr/share/responder` have the same behavior.

**Comment by noraj** [comment]
seems to be fixed now
