### ISSUE TITLE
Error while installing kubestriker

### ISSUE THREAD

**Issue by Szewcson** [BlackArch/blackarch#3522]
### Bug description

While installing kubestriker error appears. 

### Steps to reproduce
1.) Install kubestriker

- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
error:
```
Collecting SelectMenu
  Using cached SelectMenu-1.0.0b2.tar.gz (3.4 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-8l8w_h4s/selectmenu_9744cd2f74bd41b297a4dd504d26f829/setup.py", line 5, in <module>
          from selectmenu import __author__, __version__
        File "/tmp/pip-install-8l8w_h4s/selectmenu_9744cd2f74bd41b297a4dd504d26f829/selectmenu/__init__.py", line 4, in <module>
          from selectmenu.core import SelectMenu
        File "/tmp/pip-install-8l8w_h4s/selectmenu_9744cd2f74bd41b297a4dd504d26f829/selectmenu/core.py", line 6, in <module>
          from prompt_toolkit.token import Token
        File "/usr/share/kubestriker/venv/lib/python3.10/site-packages/prompt_toolkit/__init__.py", line 16, in <module>
          from .interface import CommandLineInterface
        File "/usr/share/kubestriker/venv/lib/python3.10/site-packages/prompt_toolkit/interface.py", line 19, in <module>
          from .application import Application, AbortAction
        File "/usr/share/kubestriker/venv/lib/python3.10/site-packages/prompt_toolkit/application.py", line 8, in <module>
          from .key_binding.bindings.basic import load_basic_bindings
        File "/usr/share/kubestriker/venv/lib/python3.10/site-packages/prompt_toolkit/key_binding/bindings/basic.py", line 9, in <module>
          from prompt_toolkit.renderer import HeightIsUnknownError
        File "/usr/share/kubestriker/venv/lib/python3.10/site-packages/prompt_toolkit/renderer.py", line 11, in <module>
          from prompt_toolkit.styles import Style
        File "/usr/share/kubestriker/venv/lib/python3.10/site-packages/prompt_toolkit/styles/__init__.py", line 8, in <module>
          from .from_dict import *
        File "/usr/share/kubestriker/venv/lib/python3.10/site-packages/prompt_toolkit/styles/from_dict.py", line 9, in <module>
          from collections import Mapping
      ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
```

**Comment by D3vil0p3r** [comment]
The error above does not appear anymore during the install. Please close it.
