### ISSUE TITLE
Autopsy errors on start

### ISSUE THREAD

**Issue by Szewcson** [BlackArch/blackarch#3529]
### Bug description

After starting Autopsy it shows 5 problems. On Autopsy github I found that it can be caused by lack of OpenJFX. Unfortuneatly on arch/blackarch there is no Java8-OpenJFX and Java-OpenJFX from blackarch repo not fixing those errors. Also Autopsy shows that there is newer version available.

### Steps to reproduce
1.) Install Autopsy
2.) Change java to OpenJDK8 to be able to start it since on never Java it not start
3.)Run Autopsy

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Autopsy shows 5 problems after start:
```
java.lang.ClassNotFoundException: com.sun.javafx.PlatformUtil
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at org.netbeans.ProxyClassLoader.doFindClass(ProxyClassLoader.java:209)
Caused: java.lang.ClassNotFoundException: com.sun.javafx.PlatformUtil starting from ModuleCL@733692f4[org.sleuthkit.autopsy.corelibs] with possible defining loaders null and declared parents [org.netbeans.JarClassLoader@1a8644e8]
	at org.netbeans.ProxyClassLoader.doFindClass(ProxyClassLoader.java:211)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:125)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
Caused: java.lang.NoClassDefFoundError: com/sun/javafx/PlatformUtil
	at org.sleuthkit.autopsy.corelibs.SigarLoader.getSigar(SigarLoader.java:46)
	at org.sleuthkit.autopsy.coreutils.PlatformUtil.getPID(PlatformUtil.java:505)
	at org.sleuthkit.autopsy.coreutils.Installer.restored(Installer.java:60)
	at org.sleuthkit.autopsy.core.Installer.restored(Installer.java:373)
	at org.netbeans.core.startup.NbInstaller.loadCode(NbInstaller.java:447)
[catch] at org.netbeans.core.startup.NbInstaller.loadImpl(NbInstaller.java:370)
	at org.netbeans.core.startup.NbInstaller.access$000(NbInstaller.java:77)
	at org.netbeans.core.startup.NbInstaller$1.run(NbInstaller.java:322)
	at org.openide.filesystems.FileUtil$2.run(FileUtil.java:413)
	at org.openide.filesystems.EventControl.runAtomicAction(EventControl.java:102)
	at org.openide.filesystems.FileSystem.runAtomicAction(FileSystem.java:494)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:397)
	at org.openide.filesystems.FileUtil.runAtomicAction(FileUtil.java:417)
	at org.netbeans.core.startup.NbInstaller.load(NbInstaller.java:319)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1449)
	at org.netbeans.ModuleManager.enable(ModuleManager.java:1254)
	at org.netbeans.core.startup.ModuleList.installNew(ModuleList.java:315)
	at org.netbeans.core.startup.ModuleList.trigger(ModuleList.java:251)
	at org.netbeans.core.startup.ModuleSystem.restore(ModuleSystem.java:298)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:156)
	at org.netbeans.core.startup.Main.getModuleSystem(Main.java:125)
	at org.netbeans.core.startup.Main.start(Main.java:282)
	at org.netbeans.core.startup.TopThreadGroup.run(TopThreadGroup.java:98)
	at java.lang.Thread.run(Thread.java:750)

```
```
Error in RequestProcessor org.sleuthkit.autopsy.timeline.OnStart
Caused by: javafx/application/Platform
```
```
Error in RequestProcessor org.sleuthkit.autopsy.imagegallery.OnStart
Caused by: javafx/application/Platform
```
` Some features will not be available.  Check that you have JavaFX installed (OpenJFX 8).`
`Could not start Solr server process`
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
AUtopsy start without errors

**Comment by noraj** [comment]
Java 8 is deprecated (https://www.oracle.com/java/technologies/java-se-support-roadmap.html) and is in AUR https://wiki.archlinux.org/title/Java#OpenJFX. Here is the upstream issue asking to upgrade autopsy to use mroe recent Java version https://github.com/sleuthkit/autopsy/issues/5817

**Comment by D3vil0p3r** [comment]
Autopsy seems to work with Java 21. There is an issue on `sleuthkit-java` BA package that caused issue on Autopsy. The related `sleuthkit-java` PKGBUILD is 4.12.1 but the actual package is 4.11. @noptrix can you please rebuild `sleuthkit-java` to be sure we get 4.12.1?

**Comment by noraj** [comment]
please test, I don't have much time right now

**Comment by D3vil0p3r** [comment]
Tested. It seems to work.

**Comment by noptrix** [comment]
confirmed
