### ISSUE TITLE
python pip error

### ISSUE THREAD

**Issue by Shadow-XT** [BlackArch/blackarch#3544]
- [x] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

I use the wsl version of BlackArch. When I use the pip related command in the command line, it will report an error. It seems that the Python version is confused, which occurs after I use the "sudo pacman - S blackarch" command to install

### Steps to reproduce

- using "pip install pyexecjs"

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
***Console error message 
[shine@Shadow]-[~]
&gt;&gt;&gt; pip install pyexecjs
Defaulting to user installation because normal site-packages is not writeable
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 167, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 315, in run
    session = self.get_default_session(options)
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 98, in get_default_session
    self._session = self.enter_context(self._build_session(options))
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 125, in _build_session
    session = PipSession(
  File "/usr/lib/python3.10/site-packages/pip/_internal/network/session.py", line 343, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/usr/lib/python3.10/site-packages/pip/_internal/network/session.py", line 175, in user_agent
    setuptools_dist = get_default_environment().get_distribution("setuptools")
  File "/usr/lib/python3.10/site-packages/pip/_internal/metadata/__init__.py", line 75, in get_default_environment
    return select_backend().Environment.default()
  File "/usr/lib/python3.10/site-packages/pip/_internal/metadata/__init__.py", line 63, in select_backend
    from . import pkg_resources
  File "/usr/lib/python3.10/site-packages/pip/_internal/metadata/pkg_resources.py", line 8, in <module>
    from pip._vendor import pkg_resources
  File "/usr/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3277, in _initialize_master_working_set
    tuple(
  File "/usr/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3278, in <genexpr>
    dist.activate(replace=False)
  File "/usr/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2785, in activate
    declare_namespace(pkg)
  File "/usr/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2284, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2217, in _handle_ns
    loader.load_module(packageName)
  File "/usr/lib/python3.10/site-packages/pygoogle/google.py", line 113
    print """PyGoogle %(__version__)s
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
After executing the "pip install pyexecjs" command, the console should display the installation process correctly and successfully

### Screenshots

![image](https://user-images.githubusercontent.com/65745507/193444441-9f4bbd5e-7828-4e63-8efe-6d638e7a999f.png)
![image](https://user-images.githubusercontent.com/65745507/193444412-b0f4215e-590b-4201-9d84-bbad8c2ba2b5.png)

### Info for developers

**Tool version:** Python3.10

**Comment by noraj** [comment]
> I use the wsl version of BlackArch.

There is no official BlackArch version for WSL, nor there is any official ArchLinux in MS Store. So it's not supported. Install BA in a VM instead.

> which occurs after I use the "sudo pacman - S blackarch" command to install

It's recommanded to never do that as it will try to install all 2800+ tools from BA including the ones that are outdated/depracted/broken etc.

> ```
> File "/usr/lib/python3.10/site-packages/pygoogle/google.py", line 113
> print """PyGoogle %(version)s
> ```

Are you trying to run a python 2 tool with python 3?
