### ISSUE TITLE
Bloodhound - compile error - 'ERR_OSSL_EVP_UNSUPPORTED'

### ISSUE THREAD

**Issue by D3vil0p3r** [BlackArch/blackarch#3674]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

I tested the compilation of Bloodhound package by `ba-dev` tool and the compilation returns the following error:
```
(14/15) Updating icon theme caches...
(15/15) Updating the desktop file MIME type cache...
==> Retrieving sources...
  -> Found 4.2.0.tar.gz
  -> Found bloodhound.desktop
==> WARNING: Skipping all source file integrity checks.
==> Extracting sources...
  -> Extracting 4.2.0.tar.gz with bsdtar
==> Starting build()...
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'bloodhound@4.2.0',
npm WARN EBADENGINE   required: { node: '~16' },
npm WARN EBADENGINE   current: { node: 'v19.4.0', npm: '8.19.2' }
npm WARN EBADENGINE }
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated source-map-url@0.4.0: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated source-map-resolve@0.5.2: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated xlsx@0.7.12: this version is no longer supported.  More info at https://cdn.sheetjs.com/xlsx/
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated core-js@1.2.7: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.

added 1181 packages, and audited 1182 packages in 2m

88 packages are looking for funding
  run `npm fund` for details

34 vulnerabilities (1 low, 6 moderate, 23 high, 4 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
npm notice 
npm notice New major version of npm available! 8.19.2 -> 9.2.0
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.2.0>
npm notice Run `npm install -g npm@9.2.0` to update!
npm notice 

> bloodhound@4.2.0 build:linux
> run-s compile package:linux


> bloodhound@4.2.0 compile
> webpack --config webpack.config.production.js

node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/build/bloodhound/src/BloodHound-4.2.0/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/build/bloodhound/src/BloodHound-4.2.0/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/build/bloodhound/src/BloodHound-4.2.0/node_modules/webpack/lib/NormalModule.js:471:10)
    at /build/bloodhound/src/BloodHound-4.2.0/node_modules/webpack/lib/NormalModule.js:503:5
    at /build/bloodhound/src/BloodHound-4.2.0/node_modules/webpack/lib/NormalModule.js:358:12
    at /build/bloodhound/src/BloodHound-4.2.0/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/build/bloodhound/src/BloodHound-4.2.0/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/build/bloodhound/src/BloodHound-4.2.0/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /build/bloodhound/src/BloodHound-4.2.0/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/build/bloodhound/src/BloodHound-4.2.0/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /build/bloodhound/src/BloodHound-4.2.0/node_modules/babel-loader/lib/index.js:59:71 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v19.4.0
ERROR: "compile" exited with 1.
==> ERROR: A failure occurred in build().
    Aborting...
==> ERROR: Build failed, check /home/athena/blackarch_chroot/blackarch/build
Failed to build the package.
```

**Comment by D3vil0p3r** [comment]
Solved by running `export NODE_OPTIONS=--openssl-legacy-provider` before the compiling. Should it be put in `prepare()` function of the `PKGBUILD`?
