### ISSUE TITLE
[BUG] PIP breaks when tools with python-pygoogle and python-protobuf are installed together

### ISSUE THREAD

**Issue by D3vil0p3r** [BlackArch/blackarch#3681]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

Hello, when a user installs tools with `python-pygoogle` AND `python-protobuf` dependencies, when the user tries to use `pip` command for any usage (for example `pip install <packagename>` or `pip show <packagename>`), the following error is produced:
```
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/lib/python3.10/site-packages/pip/_internal/commands/show.py", line 45, in run
    if not print_results(
  File "/usr/lib/python3.10/site-packages/pip/_internal/commands/show.py", line 148, in print_results
    for i, dist in enumerate(distributions):
  File "/usr/lib/python3.10/site-packages/pip/_internal/commands/show.py", line 78, in search_packages_info
    env = get_default_environment()
  File "/usr/lib/python3.10/site-packages/pip/_internal/metadata/__init__.py", line 75, in get_default_environment
    return select_backend().Environment.default()
  File "/usr/lib/python3.10/site-packages/pip/_internal/metadata/__init__.py", line 63, in select_backend
    from . import pkg_resources
  File "/usr/lib/python3.10/site-packages/pip/_internal/metadata/pkg_resources.py", line 8, in <module>
    from pip._vendor import pkg_resources
  File "/usr/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3277, in _initialize_master_working_set
    tuple(
  File "/usr/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3278, in <genexpr>
    dist.activate(replace=False)
  File "/usr/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2785, in activate
    declare_namespace(pkg)
  File "/usr/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2284, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2217, in _handle_ns
    loader.load_module(packageName)
  File "/usr/lib/python3.10/site-packages/pygoogle/google.py", line 113
    print """PyGoogle %(__version__)s
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
```
So `pip` becomes impossible to use. For restoring the previous state, the user must remove `python-pygoogle` OR `python-protobuf` package.

In BlackArch repository:

* the following packages are dependent on `python-pygoogle`: `manticore`, `python-pygoogle-simple` (note that `manticore` also belongs to the list of broken packages)
* the following packages are dependent on `python-protobuf`: 
  * `angr`, that is a dependency of: `angr-management`, `angrop` (that is a dependency of `rex`), `zeratool` (broken pkg)
  *  `python-google-cloud-storage`, that is a dependency of: `gcpbucketbrute`
  *  `python-unfurl`, that is a dependency of: `sooty`

Furthermore, also all packages that have as dependency `mitmproxy` will install `python-protobuf` (because it is a dependency of `mitmproxy`). These packages are: `badkarma`, `bdfproxy`, `capfuzz`, `expose`, `fs-nyarl`, `needle`, `netscan2`, `python-http-tools`, `snapception`, `snoopy-ng`, `wapiti`, `zarp`.

About these packages, `python-http-tools` is a dependency of `mobsf`; `wapiti` is a dependency of `rapidscan` and `sn1per`.

Now, my doubt is: which is the problematic package? `python-pygoogle` or `python-protobuf` or both? In my opinion, maybe the problematic package should be `python-pygoogle` because from the error, it seems to be written in Python2 code despite it is in `python3.10` library folder. This issue occurs only when `python-protobuf` is installed too. Could it be because `python-protobuf` uses `python-pygoogle` lib?

### Steps to reproduce

- Install one tool dependent on `python-pygoogle` (i.e., `manticore`) and one tool dependent on `python-protobuf` (i.e., `expose`), so `sudo pacman -S manticore expose`;
- Run a pip command as `pip show requests`;
- You will get the error.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
Error message:
```
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
  File "/usr/lib/python3.10/site-packages/pip/_internal/commands/show.py", line 45, in run
    if not print_results(
  File "/usr/lib/python3.10/site-packages/pip/_internal/commands/show.py", line 148, in print_results
    for i, dist in enumerate(distributions):
  File "/usr/lib/python3.10/site-packages/pip/_internal/commands/show.py", line 78, in search_packages_info
    env = get_default_environment()
  File "/usr/lib/python3.10/site-packages/pip/_internal/metadata/__init__.py", line 75, in get_default_environment
    return select_backend().Environment.default()
  File "/usr/lib/python3.10/site-packages/pip/_internal/metadata/__init__.py", line 63, in select_backend
    from . import pkg_resources
  File "/usr/lib/python3.10/site-packages/pip/_internal/metadata/pkg_resources.py", line 8, in <module>
    from pip._vendor import pkg_resources
  File "/usr/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3252, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3277, in _initialize_master_working_set
    tuple(
  File "/usr/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3278, in <genexpr>
    dist.activate(replace=False)
  File "/usr/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2785, in activate
    declare_namespace(pkg)
  File "/usr/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2284, in declare_namespace
    _handle_ns(packageName, path_item)
  File "/usr/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2217, in _handle_ns
    loader.load_module(packageName)
  File "/usr/lib/python3.10/site-packages/pygoogle/google.py", line 113
    print """PyGoogle %(__version__)s
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
```

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)
In case of `pip show requests` example command:
```
Name: requests
Version: 2.28.1
Summary: Python HTTP for Humans.
Home-page: https://requests.readthedocs.io
Author: Kenneth Reitz
Author-email: me@kennethreitz.org
License: Apache 2.0
Location: /usr/lib/python3.10/site-packages
Requires: idna, urllib3
Required-by: 
```

**Comment by noraj** [comment]
[python-protobuf](https://archlinux.org/packages/extra/x86_64/python-protobuf/) is from AL. And [python-pygoogle](https://github.com/BlackArch/blackarch/blob/master/packages/python-pygoogle/PKGBUILD) is in BA but built from [pygoogle](https://pypi.org/project/pygoogle/) that has not been updated since 2006.

```
$ pacman -Sii python-pygoogle
...                                                                                                                                                                                     
Required By     : manticore
```

`python-pygoogle` is required only by `manticore` but looking at https://github.com/trailofbits/manticore/blob/master/setup.py pygoogle is no longer required.

**Comment by D3vil0p3r** [comment]
Ok. I will open a PR with the updated dependencies and adding also wasm Python module. I'm aware of https://github.com/trailofbits/manticore/issues/1426 Maybe we can keep the PR opened until the `z3-solver` issue is fixed.

**Comment by noraj** [comment]
> Ok. I will open a PR with the updated dependencies and adding also wasm Python module. I'm aware of [trailofbits/manticore#1426](https://github.com/trailofbits/manticore/issues/1426) Maybe we can keep the PR opened until the `z3-solver` issue is fixed.

I'm was working on it and will provide a PR, that I hope, will fix everything.
