### ISSUE TITLE
using evil-winrm - Error: OpenSSL::Digest::DigestError

### ISSUE THREAD

**Issue by ultiMEIGHT** [BlackArch/blackarch#3716]
I am getting the following error while using evil-winrm.
### Error
```
Error: An error of type OpenSSL::Digest::DigestError happened, message is Digest initialization failed: initialization error

Error: Exiting with code 1
```
I have installed evil-winrm by running the following command:
`gem install evil-winrm`

As suggested by @DF001 in [this](https://github.com/BlackArch/blackarch/issues/3593) post, I made the changes to /etc/ssl/openssl.cnf but that gives the following runtime error when using the tool:

```
<internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': OPENSSL_init_ssl (RuntimeError)
        from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /usr/lib/ruby/3.0.0/openssl.rb:13:in `<top (required)>'
        from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/an4rki/.local/share/gem/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient/ssl_config.rb:12:in `<class:HTTPClient>'
        from /home/an4rki/.local/share/gem/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient/ssl_config.rb:9:in `<top (required)>'
        from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/an4rki/.local/share/gem/ruby/3.0.0/gems/httpclient-2.8.3/lib/httpclient.rb:15:in `<top (required)>'
        from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/an4rki/.local/share/gem/ruby/3.0.0/gems/winrm-2.3.6/lib/winrm/http/transport.rb:15:in `<top (required)>'
        from /home/an4rki/.local/share/gem/ruby/3.0.0/gems/winrm-2.3.6/lib/winrm/http/transport_factory.rb:15:in `require_relative'
        from /home/an4rki/.local/share/gem/ruby/3.0.0/gems/winrm-2.3.6/lib/winrm/http/transport_factory.rb:15:in `<top (required)>'
        from /home/an4rki/.local/share/gem/ruby/3.0.0/gems/winrm-2.3.6/lib/winrm/connection.rb:16:in `require_relative'
        from /home/an4rki/.local/share/gem/ruby/3.0.0/gems/winrm-2.3.6/lib/winrm/connection.rb:16:in `<top (required)>'
        from /home/an4rki/.local/share/gem/ruby/3.0.0/gems/winrm-2.3.6/lib/winrm.rb:17:in `require_relative'
        from /home/an4rki/.local/share/gem/ruby/3.0.0/gems/winrm-2.3.6/lib/winrm.rb:17:in `<top (required)>'
        from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/an4rki/.local/share/gem/ruby/3.0.0/gems/evil-winrm-3.4/evil-winrm.rb:8:in `<top (required)>'
        from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/usr/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /home/an4rki/.local/share/gem/ruby/3.0.0/gems/evil-winrm-3.4/bin/evil-winrm:3:in `<top (required)>'
        from /home/an4rki/.local/share/gem/ruby/3.0.0/bin/evil-winrm:25:in `load'
        from /home/an4rki/.local/share/gem/ruby/3.0.0/bin/evil-winrm:25:in `<main>'
```

I did a full system upgrade (pacman -Syu) before trying again, but that did not resolve the issue.

**Comment by noraj** [comment]
> I have installed evil-winrm by running the following command:
> `gem install evil-winrm`

Then it's not using BA package.

```
gem uninstall evil-winrm
pacman -Syu evil-winrm
```
