### ISSUE TITLE
Empire runtime crash

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#3790]
```
➜ empire-server                                   
Traceback (most recent call last):
  File "/usr/share/empire/empire.py", line 11, in <module>
    import empire.server.server as server
  File "/usr/share/empire/empire/server/server.py", line 26, in <module>
    import socketio
  File "/usr/lib/python3.10/site-packages/socketio/__init__.py", line 9, in <module>
    from .zmq_manager import ZmqManager
  File "/usr/lib/python3.10/site-packages/socketio/zmq_manager.py", line 5, in <module>
    import eventlet.green.zmq as zmq
  File "/usr/lib/python3.10/site-packages/eventlet/__init__.py", line 17, in <module>
    from eventlet import convenience
  File "/usr/lib/python3.10/site-packages/eventlet/convenience.py", line 7, in <module>
    from eventlet.green import socket
  File "/usr/lib/python3.10/site-packages/eventlet/green/socket.py", line 4, in <module>
    __import__('eventlet.green._socket_nodns')
  File "/usr/lib/python3.10/site-packages/eventlet/green/_socket_nodns.py", line 11, in <module>
    from eventlet import greenio
  File "/usr/lib/python3.10/site-packages/eventlet/greenio/__init__.py", line 3, in <module>
    from eventlet.greenio.base import *  # noqa
  File "/usr/lib/python3.10/site-packages/eventlet/greenio/base.py", line 473, in <module>
    from OpenSSL import SSL
  File "/usr/share/empire/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/share/empire/OpenSSL/crypto.py", line 1517, in <module>
    class X509StoreFlags(object):
  File "/usr/share/empire/OpenSSL/crypto.py", line 1537, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
```

It seems to be an issue from `pyopenssl` when only `openssl 3.0.8-1` is installed. It probably still relies on the old `openssl-1.1 1.1.1.t-1`. Installing `openssl-1.1` alone doesn't solve the issue.

**Comment by noraj** [comment]
- https://github.com/BlackArch/blackarch/blob/ab541d0b29dc8af3766eb4daa3e4586a77e88672/packages/empire/PKGBUILD#L27
- https://github.com/BlackArch/blackarch/blob/ab541d0b29dc8af3766eb4daa3e4586a77e88672/packages/empire/PKGBUILD#L43

I see, this is probably due to the hard-coded version. It seems outdated since https://github.com/BC-SECURITY/Empire/blob/e782c806887aa57842793d71ad60355da93a0684/poetry.lock#L1462-L1472 requires v 22 and not 19.5 anymore. AL repo offers `python-pyopenssl 23.1.1-1`. Maybe we should repackage it in a virtual environment to avoid managing the many dependencies issue as well as outdated and conflicting dependencies of Empire.

**Comment by noptrix** [comment]
@noraj can you try again, please?

**Comment by noraj** [comment]
https://github.com/BlackArch/blackarch/commit/a602f9a37f9688371d302c8f2002b126edcfaf7f seems to fix the pyopenssl issue. Now it can tell me it misses a dependency.

```
➜ empire-server
Traceback (most recent call last):
  File "/usr/share/empire/empire.py", line 11, in <module>
    import empire.server.server as server
  File "/usr/share/empire/empire/server/server.py", line 14, in <module>
    from empire.server.api import app
  File "/usr/share/empire/empire/server/api/app.py", line 16, in <module>
    from empire.server.api.v2.websocket.socketio import setup_socket_events
  File "/usr/share/empire/empire/server/api/v2/websocket/socketio.py", line 7, in <module>
    from empire.server.api import jwt_auth
  File "/usr/share/empire/empire/server/api/jwt_auth.py", line 6, in <module>
    from jose import JWTError, jwt
ModuleNotFoundError: No module named 'jose'
```

**Comment by noptrix** [comment]
@noraj thank you very much - i am gonna fix that.

**Comment by noraj** [comment]
@noptrix thank you for fixing it, I'm sorry I can't do it myself at the moment

**Comment by noptrix** [comment]
@noraj will let you know so you can retest - added tons of dependencies. if it doesn't work in the first shot i think time has come to switch to venv then.

**Comment by noraj** [comment]
mariadb initialized and running:

<details>
<summary>Error trace</summary>

```
➜ empire-server
(pymysql.err.OperationalError) (1045, "Access denied for user 'empire_user'@'localhost' (using password: YES)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 325, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 888, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 491, in checkout
    rec = pool._do_get()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/usr/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 210, in raise_
    raise exception
  File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 271, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 386, in __init__
    self.__connect()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 684, in __connect
    with util.safe_reraise():
  File "/usr/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 210, in raise_
    raise exception
  File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 680, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/usr/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "/usr/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "/usr/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/usr/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1045, "Access denied for user 'empire_user'@'localhost' (using password: YES)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/share/empire/empire/server/core/db/base.py", line 35, in try_create_engine
    with engine.connect():
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3315, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3394, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3364, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2198, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 210, in raise_
    raise exception
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3361, in _wrap_pool_connect
    return fn()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 325, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 888, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 491, in checkout
    rec = pool._do_get()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/usr/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 210, in raise_
    raise exception
  File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 271, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 386, in __init__
    self.__connect()
  File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 684, in __connect
    with util.safe_reraise():
  File "/usr/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 210, in raise_
    raise exception
  File "/usr/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 680, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 578, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/lib/python3.10/site-packages/pymysql/connections.py", line 352, in __init__
    self.connect()
  File "/usr/lib/python3.10/site-packages/pymysql/connections.py", line 636, in connect
    self._request_authentication()
  File "/usr/lib/python3.10/site-packages/pymysql/connections.py", line 911, in _request_authentication
    auth_packet = self._read_packet()
  File "/usr/lib/python3.10/site-packages/pymysql/connections.py", line 729, in _read_packet
    packet.raise_for_error()
  File "/usr/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/usr/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
sqlalchemy.exc.OperationalError: (pymysql.err.OperationalError) (1045, "Access denied for user 'empire_user'@'localhost' (using password: YES)")
(Background on this error at: https://sqlalche.me/e/14/e3q8)
Failed connecting to database using mysql+pymysql://empire_user:empire_password@localhost:3306
Perhaps the MySQL service is not running.
Try executing: sudo systemctl start mysql
```

</details>

The setup_database.py is not called https://github.com/BlackArch/blackarch/blob/7c72fa0dd7f909106851e882a70c2632ba8f49d1/packages/empire/PKGBUILD#L45

It's possible it was removed and replaced with https://github.com/BC-SECURITY/Empire/blob/main/setup/install.sh#L78-L91
