### ISSUE TITLE
wapiti not working due to "No package metadata was found for wapiti3"

### ISSUE THREAD

**Issue by D3vil0p3r** [BlackArch/blackarch#3830]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

When `wapiti` is installed and run, the user gets the following error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/wapiti", line 33, in <module>
    sys.exit(load_entry_point('wapiti3==3.1.6', 'console_scripts', 'wapiti')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/wapiti", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for wapiti3
```
Furthermore, wapiti needs to be updated. I tried to create a PKGBUILD for the updated version but it fails during the building:
```PKGBUILD
# This file is part of BlackArch Linux ( https://www.blackarch.org/ ).
# See COPYING for license details.

pkgname=wapiti
pkgver=3.1.7.r11.gd421a59
pkgrel=1
groups=('blackarch' 'blackarch-webapp' 'blackarch-scanner' 'blackarch-fuzzer')
pkgdesc='A vulnerability scanner for web applications.'
url='https://github.com/wapiti-scanner/wapiti'
license=('GPL')
depends=('python' 'mitmproxy' 'python-aiocache' 'python-aiohttp' 'python-aiosqlite' 'python-arsenic' 'python-beautifulsoup4' 'python-brotli' 'python-browser-cookie3' 'python-dnspython' 'python-h11' 'python-httpcore' 'python-httpx-socks' 'python-loguru' 'python-mako' 'python-markupsafe' 'python-pyasn1' 'python-six' 'python-sqlalchemy' 'python-tld' 'python-yaswfp')
makedepends=('git' 'python-setuptools' 'python-wheel' 'python-pip')
checkdepends=('python-humanize' 'python-pytest' 'python-pytest-cov' 'python-pytest-asyncio' 'sslyze' 'python-pydantic')
arch=('any')
source=("git+https://github.com/wapiti-scanner/$pkgname.git")
sha512sums=('SKIP')

pkgver() {
  cd $pkgname

  git describe --long --tags | sed 's/\([^-]*-g\)/r\1/;s/-/./g'
}

build() {
  cd $pkgname

  python -m build --wheel --outdir="$startdir/dist"
}

package() {
  cd $pkgname

  pip install \
    --verbose \
    --disable-pip-version-check \
    --no-warn-script-location \
    --ignore-installed \
    --no-compile \
    --no-deps \
    --root="$pkgdir" \
    --prefix=/usr \
    --no-index \
    --find-links="file://$startdir/dist" \
    "$pkgname"
}

```

### Steps to reproduce

- Run `sudo pacman -S wapiti`
- Run `wapiti`

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)

The error described above.

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

Wapiti working correctly.

**Comment by saltasatelites** [comment]
Hi.
Check if you have the package python-importlib-metadata installed.

**Comment by D3vil0p3r** [comment]
> Hi. Check if you have the package python-importlib-metadata installed.

It should be added in depends list of its PKGBUILD then.

**Comment by D3vil0p3r** [comment]
Fixed
