### ISSUE TITLE
objection broken

### ISSUE THREAD

**Issue by dualfade** [BlackArch/blackarch#3945]
- objection package is broken
- please see output below

[objection github link](https://github.com/sensepost/objection)

```bash
~ % objection -h
Traceback (most recent call last):
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/objection", line 33, in <module>
    sys.exit(load_entry_point('objection==1.11.0', 'console_scripts', 'objection')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/objection", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for objection
```

- **Note:** Installed from virtualenv and works fine. 
- Need to update and test new PKGBUILD.

**Comment by dualfade** [comment]
Some other issues going on here. Will need to investigate more.

**Comment by PardesiCat** [comment]
Hei am newbie  dont mind me 

but saw this so thought maybe my suggestion could help


what if use this [PKGBUILD ](https://git.pardesicat.xyz/pardesicat/blackarch-objection)  to pack the objection tool 

for me working fine , dont mind just check and give feedback

**Comment by dualfade** [comment]
Great ! Will test it out. Thank you.
