### ISSUE TITLE
zsteg: broken due to outdated `ruby-iostruct` dependency

### ISSUE THREAD

**Issue by 135e2** [BlackArch/blackarch#4166]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description

`zsteg` fails to run with outdated dependency `ruby-iostruct` 0.0.4:

```
/usr/lib/ruby/3.0.0/rubygems/specification.rb:1453:in `rescue in block in activate_dependencies': Could not find 'iostruct' (>= 0.0.5) among 90 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/home/shang/.local/share/gem/ruby/3.0.0:/usr/lib/ruby/gems/3.0.0' at: /usr/lib/ruby/gems/3.0.0/specifications/zsteg-0.2.13.gemspec, execute `gem env` for more information
        from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1450:in `block in activate_dependencies'
        from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1439:in `each'
        from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1439:in `activate_dependencies'
        from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1421:in `activate'
        from /usr/lib/ruby/3.0.0/rubygems.rb:286:in `block in activate_bin_path'
        from /usr/lib/ruby/3.0.0/rubygems.rb:285:in `synchronize'
        from /usr/lib/ruby/3.0.0/rubygems.rb:285:in `activate_bin_path'
        from /usr/bin/zsteg:25:in `<main>'
/usr/lib/ruby/3.0.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'iostruct' (>= 0.0.5) - did find: [iostruct-0.0.4] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/home/shang/.local/share/gem/ruby/3.0.0:/usr/lib/ruby/gems/3.0.0' , execute `gem env` for more information
        from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1451:in `block in activate_dependencies'
        from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1439:in `each'
        from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1439:in `activate_dependencies'
        from /usr/lib/ruby/3.0.0/rubygems/specification.rb:1421:in `activate'
        from /usr/lib/ruby/3.0.0/rubygems.rb:286:in `block in activate_bin_path'
        from /usr/lib/ruby/3.0.0/rubygems.rb:285:in `synchronize'
        from /usr/lib/ruby/3.0.0/rubygems.rb:285:in `activate_bin_path'
        from /usr/bin/zsteg:25:in `<main>'
```

The `ruby-iostruct` PKGBUILD seems to be [updated regularly](https://github.com/BlackArch/blackarch/commit/e8d3c4a55f6527f2d829c06f5b6fab055c9ec521), but never gets built and uploaded to the official blackarch repo. A re-build and re-upload would fix the problem.
### Steps to reproduce

- `paru -S zsteg`, downloads dependency [ruby-iostruct-0.0.4-1](https://www.blackarch.org/blackarch/blackarch/os/x86_64/ruby-iostruct-0.0.4-1-any.pkg.tar.zst)
- program fails to start

**Actual result:** zsteg broken w/ ruby-iostruct-0.0.4

**Expected result:** zsteg runs w/ ruby-iostruct >= 0.0.5

### Info for developers

**GNU/Linux distribution:** Archlinux
**Tool version:** v0.2.13.r5.g8fc7798-1

**Comment by 135e2** [comment]
`ruby-iostruct` PKGBUILD is [broken with a typo](https://github.com/BlackArch/blackarch/commit/718a1cc7f4ca5fe7948edd776e9834874288f592#diff-f2c382cccd32282c85f4b35d2d3cf845e5cced3f76940cadb8c5d061a8b4241fR13) and never buiilt successfully.
Rename `$_pkgname` to `$_gemname` would fix.
