### ISSUE TITLE
`arjun` package misses `python-ratelimit` dependency

### ISSUE THREAD

**Issue by nil0x42** [BlackArch/blackarch#4331]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended

----------------------------------------

### Bug description
arjun package misses `python-ratelimit` dependency:
```
$ arjun -u <URL>
    _
   /_| _ '
  (  |/ /(//) v2.2.6
      _/      

Traceback (most recent call last):
  File "/usr/sbin/arjun", line 33, in <module>
    sys.exit(load_entry_point('arjun==2.2.6', 'console_scripts', 'arjun')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/sbin/arjun", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/usr/lib/python3.12/site-packages/arjun/__main__.py", line 90, in <module>
    from arjun.core.requester import requester
  File "/usr/lib/python3.12/site-packages/arjun/core/requester.py", line 9, in <module>
    from ratelimit import limits, sleep_and_retry
ModuleNotFoundError: No module named 'ratelimi
```

### Steps to reproduce

- install arjun
- try to use it

### Info for developers

I would have submitted a pull request with the updated pkgfile, but since python-ratelimit is only available on AUR, it may need to be packaged in BlackArch. I’m unsure of the best way to proceed with this.

**Comment by D3vil0p3r** [comment]
https://github.com/BlackArch/blackarch/pull/4332
