### ISSUE TITLE
Semgrep: missing dependency

### ISSUE THREAD

**Issue by noraj** [BlackArch/blackarch#4392]
Scanner does not work due to missing dependency:

```

Traceback (most recent call last):
  File "/usr/bin/pysemgrep", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/semgrep/console_scripts/pysemgrep.py", line 52, in main
    sys.exit(semgrep.main.main())
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/semgrep/main.py", line 115, in main
    from semgrep.cli import cli
  File "/usr/lib/python3.12/site-packages/semgrep/cli.py", line 5, in <module>
    from semgrep.commands.ci import ci
  File "/usr/lib/python3.12/site-packages/semgrep/commands/ci.py", line 21, in <module>
    import semgrep.app.auth as auth
  File "/usr/lib/python3.12/site-packages/semgrep/app/auth.py", line 7, in <module>
    from semgrep import tracing
  File "/usr/lib/python3.12/site-packages/semgrep/tracing.py", line 16, in <module>
    from opentelemetry import context
ModuleNotFoundError: No module named 'opentelemetry'
```

The new dependencies were introduces in July https://github.com/semgrep/semgrep/commit/2903f9a29d2a89c3edd33e653f3bfda516f42c79#diff-ec5d2c5f6329375538e730b11d4c310e617eb6247a77103ed79ffe1ec3336097

However, they are not packaged on AL or BA. I'm not sure it's worth package the 4 dependencies, if semgrep is constantly removing and adding dependencies, maybe our best move would be to miragte to a virtual env package.

**Comment by noptrix** [comment]
i've downgradet it to the latest working version (1.79.0) for now. i agree, then it's time for a venv. feel free to add it.
