### ISSUE TITLE
[bletchley] fails to run.

### ISSUE THREAD

**Issue by paraxor** [BlackArch/blackarch#469]
Error:

    Traceback (most recent call last):
      File "/usr/bin/bletchley-analyze", line 28, in <module>
        from bletchley import blobtools,buffertools
    ImportError: No module named 'bletchley'

**Comment by Kishaihd** [comment]
I get this same error. 

Traceback (most recent call last):
  File "/usr/bin/bletchley-decode", line 27, in <module>
    from bletchley import blobtools
ModuleNotFoundError: No module named 'bletchley'
